### ISSUE TITLE
[Feature Request]: filter task by "Save Path" or part of the string of the "Save Path"

### ISSUE THREAD

**Issue by tainewoo** [VueTorrent/VueTorrent#1013]
Currently we only can order the tasks by the "Save Path", but we can't filter the tasks by the "Save Path" or part of the string of the "Save Path".
Normally we will have some of the tasks which having the same "Name", same "Save Path", or same root folder of the "Save Path"
This feature is quite important for PT users to manage the tasks, such as when they are moving the files, checking the missed tasks for some of the PT sites, etc.
Please help consider implement this feature.
Thanks so much!

**Comment by tainewoo** [comment]
Supposed we can have an filter option, the type is text, field name is "save path".
Users can input part of the path, such as: /volume1/savepath1/temp
After a short delay, UI started to filter all torrents, and list the torrents that "save path" contains the string user input in this field.

**Comment by WDaan** [comment]
This used to be possible with the old quick search.

Know the functionality is more limited to be more performant. But I still think searching should be improved upon to be fuzzy once again, ideally without losing out on performance too much.

#541
