### ISSUE TITLE
[Feature Request] Batch edit trackers

### ISSUE THREAD

**Issue by flashlab** [VueTorrent/VueTorrent#1100]
In qb client version, we can do like this
![img](https://camo.githubusercontent.com/35a7558f01f6a9cea09577ab85e581bcc3caeeb8/68747470733a2f2f692e6962622e636f2f625154725233512f712d426974746f72656e742d656469742d747261636b6572732d6d756c74692d746f7272656e74732e706e67)
But official webui is missing such function.
We can achieve it by https://github.com/qbittorrent/qBittorrent/issues/18539, but programming knowledge is needed.
Or we can do it in the bowser like https://github.com/qbittorrent/qBittorrent/issues/11868 discussed.

It will be great if we can batch add/remove/edit trackers on web ui. The most cases among PT user is:

- change passkey string
- change domain name
- remove discarded one
- add new one

Thanks

**Comment by maxiwheat** [comment]
That would be awesome if this could be added

**Comment by Larsluph** [comment]
Batch edit seems complicated except if we make it like "change location", first loaded value is the first selected torrent and on submit, we just replace everything.
And even for that "simple" behavior, it is not possible natively.

The only routes in the qbit API are:
- Add tracker to torrent
- Remove tracker to torrent
- Replace single tracker with another on a torrent

So one thing we can do is make a batch edit that mixes these 3 possible behaviors in the same interface, which can be something like that:
```
+trackerToAdd1
+trackerToAdd2
-trackerToRemove1
-trackerToRemove2
~trackerToEditOld|trackerToEditNew
```

**Comment by draco1544** [comment]
Any news on that ?

**Comment by Larsluph** [comment]
I haven't heard of anyone working on the subject.

Remember that this project is an open-source initiative, and all contributions are made on a voluntary basis.

Requested features may never be implemented at the end...

**Comment by draco1544** [comment]
> In qb client version, we can do like this
> 
> ![img](https://camo.githubusercontent.com/35a7558f01f6a9cea09577ab85e581bcc3caeeb8/68747470733a2f2f692e6962622e636f2f625154725233512f712d426974746f72656e742d656469742d747261636b6572732d6d756c74692d746f7272656e74732e706e67)
> 
> But official webui is missing such function.
> 
> We can achieve it by https://github.com/qbittorrent/qBittorrent/issues/18539, but programming knowledge is needed.
> 
> Or we can do it in the bowser like https://github.com/qbittorrent/qBittorrent/issues/11868 discussed.
> 
> 
> 
> It will be great if we can batch add/remove/edit trackers on web ui. The most cases among PT user is:
> 
> 
> 
> - change passkey string
> 
> - change domain name
> 
> - remove discarded one
> 
> - add new one
> 
> 
> 
> Thanks

The link for the picture is broken, how do we achieve that in the classic qbitorrent interface ?

**Comment by Larsluph** [comment]
> > In qb client version, we can do like this
> > 
> > ![img](https://camo.githubusercontent.com/35a7558f01f6a9cea09577ab85e581bcc3caeeb8/68747470733a2f2f692e6962622e636f2f625154725233512f712d426974746f72656e742d656469742d747261636b6572732d6d756c74692d746f7272656e74732e706e67)
> > 
> > But official webui is missing such function.
> > 
> > We can achieve it by https://github.com/qbittorrent/qBittorrent/issues/18539, but programming knowledge is needed.
> > 
> > Or we can do it in the bowser like https://github.com/qbittorrent/qBittorrent/issues/11868 discussed.
> > 
> > 
> > 
> > It will be great if we can batch add/remove/edit trackers on web ui. The most cases among PT user is:
> > 
> > 
> > 
> > - change passkey string
> > 
> > - change domain name
> > 
> > - remove discarded one
> > 
> > - add new one
> > 
> > 
> > 
> > Thanks
> 
> The link for the picture is broken, how do we achieve that in the classic qbitorrent interface ?

When right clicking a torrent on the torrent list you have an option to edit trackers. However you can only do it for a single torrent at a time.

**Comment by Investigamer** [comment]
Just have it replace existing trackers in the selected torrents with a list of trackers provided, changing/adding/removing is pretty much unnecessary as a bulk feature. The only typical use for this feature is to replace a private tracker URL due to a domain change. We do need this feature for this purpose, strikes me as a dealbreaker for anyone using private trackers.

**Comment by draco1544** [comment]
> Just have it replace existing trackers in the selected torrents with a list of trackers provided, changing/adding/removing is pretty much unnecessary as a bulk feature. The only typical use for this feature is to replace a private tracker URL due to a domain change. We do need this feature for this purpose, strikes me as a dealbreaker for anyone using private trackers.

I have more than 200 torrents that need a tracker replacement

**Comment by draco1544** [comment]
> Just have it replace existing trackers in the selected torrents with a list of trackers provided, changing/adding/removing is pretty much unnecessary as a bulk feature. The only typical use for this feature is to replace a private tracker URL due to a domain change. We do need this feature for this purpose, strikes me as a dealbreaker for anyone using private trackers.

Here a python script that may help you to do that:

```python
import qbittorrentapi

# API Configuration
qb = qbittorrentapi.Client(host='http://0.0.0.0:8080', username='username', password='password')

# New tracker URL to replace existing trackers
new_tracker_url = "new Tracker URL"

# Attempt to log in to qBittorrent
try:
    qb.auth_log_in()
except qbittorrentapi.LoginFailed as e:
    print(f"Connection error: {e}")
    exit(1)

# Retrieve the list of all torrents
try:
    torrents = qb.torrents_info()
except qbittorrentapi.APIError as e:
    print(f"Error retrieving torrents: {e}")
    qb.auth_log_out()
    exit(1)

# Initialize counters
total_count = len(torrents)
changed_count = 0
ignored_count = 0

# Iterate over each torrent and replace all trackers with the new URL
for torrent in torrents:
    try:
        print(f"Torrent: {torrent.name}")
        # Get the list of trackers for the current torrent
        trackers = qb.torrents_trackers(torrent.hash)
        for tracker in trackers:
            # Skip special trackers like DHT, PeX, and LSD
            if tracker.url not in ['** [DHT] **', '** [PeX] **', '** [LSD] **']:
                if tracker.url != new_tracker_url:
                    # Replace the old tracker URL with the new tracker URL
                    qb.torrents_edit_tracker(torrent_hash=torrent.hash, original_url=tracker.url, new_url=new_tracker_url)
                    print(f"  Old Tracker: {tracker.url} replaced with {new_tracker_url}")
                    changed_count += 1
                else:
                    print(f"  Torrent ignored because it already has the same tracker: {tracker.url}")
                    ignored_count += 1
        print("-")
    except qbittorrentapi.APIError as e:
        print(f"Error processing torrent {torrent.name}: {e}")

# Display summary
print(f"Total number of torrents: {total_count}")
print(f"Number of trackers replaced: {changed_count}")
print(f"Number of torrents ignored: {ignored_count}")

# Log out from qBittorrent
qb.auth_log_out()
```
