### ISSUE TITLE
Poor performance in content tab on torrents with large number of files

### ISSUE THREAD

**Issue by AlexCzar** [VueTorrent/VueTorrent#1115]
I have a torrent with a hundred southand files and thousands of folders, top level is not that bad though, it's several hundreds of folders and several dozens of top level files.

The performance of the content tab could be categorized as "unusable", the rest of the interface freezes, too, if that tab is open.

Suggestion for performance improvement here could be to only render the root of the torrent and only process and render subdirectories when requested (a directory is unfolded), with the unfolded directory do the same, only render the root.

**Comment by WDaan** [comment]
Any noticeable difference for the vue3 version?

**Comment by Larsluph** [comment]
I think the vue3 version is slower unfortunately, maybe we can improve it by using shallow refs but that means we need to refresh the content tab's display manually

**Comment by WDaan** [comment]
We could hook into folder opening and add it to the file structure object?

**Comment by AlexCzar** [comment]
Not sure, about vue3, I'm on latest-release branch of VueTorrent, which reports version 1.8.0.
The problem is very much there, it's impossible even to scroll more than a screen at a time, then the UI freezes, Firefox reports slow script, then it unfreezes, and I can scroll one screen more…

**Comment by Larsluph** [comment]
@AlexCzar vue3 version is on `nightly-release-vue3` branch

**Comment by AlexCzar** [comment]
I have zero experience with TypeScript, but I have some time this weekend, so I'll try to see what could be done to optimise it a bit.

**Comment by the-mentor** [comment]
I'm experiencing the same slowness issue with the latest version 2.2.0

**Comment by tainewoo** [comment]
Yes the performance for content of torrents have hundreds of files.
I met freeze and even "tab not responding" for some torrents have 9xx files or 1xxx files.
Before upgraded to Vue3, I can wait for couples of seconds and the content could be shown.
After upgraded to Vue3, I waited for more than 1 minutes, the browser tab was still freezing or not responding.
Compared to the original web UI, the performance is normal. So I will switch to original web ui to manage the content for this kind of torrents, and after that, switch back to VueTorrent.

**Comment by tainewoo** [comment]
The performance issue still exists on VueTorrent v2.6.0 after the new content tab is implemented.

**Comment by tainewoo** [comment]
After some test, the performance of the content tab is much better.
I tested on some torrents have dozens of files, all of them can successfully load the file list instantly, even some torrents have more than 200 files.

But I can always meet the "tab not responding" problem on a special torrent.
This torrent has only 54 files under some folders .
The content tab always got stuck.
Still don't know what's the root cause.

After that, I tried some other similar torrents.
All of them are full BDMV torrents. They will have some sub folders, and some lots of files in each sub folder.
The file number of them can be dozens, or even more than 1 thousand.
The not responding problem can be more easy to be reproduced on this kind of torrents.

While on much more other torrents, the performance of the content tab is much better now.
Thank you all for your great efforts. :)

**Comment by tainewoo** [comment]
![torrentdetail](https://github.com/VueTorrent/VueTorrent/assets/13391232/951083e9-6215-4777-b817-e4730469e2f4)


![content_notresponding](https://github.com/VueTorrent/VueTorrent/assets/13391232/d6549d79-361c-420d-bc05-de903b41e1a9)

**Comment by Larsluph** [comment]
The content tab will sometimes call the API without the torrent hash, which is causing an error. Simply reload your tab and it will resolve properly. Still need to investigate on that as well.

**Comment by tainewoo** [comment]
> The content tab will sometimes call the API without the torrent hash, which is causing an error. Simply reload your tab and it will resolve properly. Still need to investigate on that as well.

Cool, I tried to reload the page directly when the tab is stuck following your instruction, the content can be successfully loaded instantly.

Seems this performance issue is almost fix, or can be considerred as fixed.
The only we need to check is the missed hash when calling the API.

Thank you so much.

**Comment by tainewoo** [comment]
I tested on some torrents have more than 700 files, works fine (after reload the page if I met the not responding problem).
Normally we can't get the content loaded for this kind of torrent when using VueTorrent  earlier than 2.6.0.

The performance issue is solved. :)

**Comment by Larsluph** [comment]
Awesome, thanks for checking!
