### ISSUE TITLE
[Feature Request] Change Torrent Detail Tabs Order

### ISSUE THREAD

**Issue by Antonio36996** [VueTorrent/VueTorrent#1133]
When I have to rename various torrents without stopping them I need to go manually to the Content Tab to rename the file, I would like to be able to select that tab to be the first to be opened when I select the torrent. Thanks!

**Comment by Larsluph** [comment]
If your torrent has only 1 file, you can quick rename that file in the overview tab.
But the idea to configure the default tab seems great!
