### ISSUE TITLE
[Feature Request] User friendliness improvements to search and sort

### ISSUE THREAD

**Issue by Seltonu** [VueTorrent/VueTorrent#1267]
Hello! Please let me know if this discussion is welcome, I have some suggestions for user-friendliness improvements. I find myself using sort-by often, but it is cumbersome to navigate the lengthy dropdown menu when realistically I don't need most of the options. I see the dropdown was added in #309, with some further discussion on removing options in #1091 but I don't actually see a way to do so currently? I may just be missing something here, v2.0

I'd like to suggest:

- The sort-by dropdown be replaced with sort 'pills'/tabs spanning the length of unused space. This will reduce the clicks needed to sort, and reduce time spent looking for the right option, especially as the user develops muscle memory for the pills they use most frequently.
    - This would improve upon #309 further and be closer to the spirit of the original post, with quick sorting buttons
    - Can work in conjunction with #1091, allowing a user to cull unused options will prevent the design from becoming too full. Maybe some reasonable defaults can be discussed, with further sort-by options enabled in settings.
    - Lays the groundwork for #1012  Currently there wouldn't be a straightforward way to select multiple "sort-by" options with a simple dropdown menu. Expanding out into multiple pills/tabs could allow a user to toggle multiple at once.

![image](https://github.com/WDaan/VueTorrent/assets/10287568/2da33b84-194e-49ba-be2b-713b6d481db0)

- The search menu is currently also tucked away behind an extra click, and is less intuitive to users than simply having a search bar visible at all times. As the horizontal space is currently free, it seems a hopefully simple improvement to remove the icon to expand step. Maybe moving it a row higher could further make space for the sort-by changes

![image](https://github.com/WDaan/VueTorrent/assets/10287568/bf5d9d06-46ca-4997-adb3-c0cd647a59d8)

Looking forward to hearing thoughts on this

**Comment by WDaan** [comment]
It is more than welcome, if there is something you think could be done better... please speak up!

The search thing ties together with https://github.com/WDaan/VueTorrent/issues/891 where we proposed a spotify like approach for mobile and something like you're suggesting for desktop.

In this WIP [here](https://github.com/WDaan/VueTorrent/pull/1186) I was playing around with tanstack tables where we sort of would have the tabs/pills you are suggesting. You play around with an example [here](https://www.shadcn-vue.com/examples/tasks.html)

**Comment by Seltonu** [comment]
@WDaan Awesome to see progress/discussions on this! I don't use mobile but I took a look at the Spotify playlist search and that feels like a good approach for mobile

As for sorting a table view makes sense, though it seems a shame to choose between pretty UI or easier sorting. Here are some initial thoughts that jump out at me:

- I noticed it was described as a minimal view, is anything being lost functionality wise compared to the original view? Or is it just about style? Personally would be looking for columns such as sorting by up/down speed, upload amount, and still showing category/tags even if not sortable etc.
- Hopefully some of the styling is still able to make its way over to a table view for a splash of color, such as progress bars

Of course, I understand what's shown is a WIP and might not have all features shown. I'm liking the direction!

**Comment by WDaan** [comment]
Well I was thinking of using the table to solve: https://github.com/WDaan/VueTorrent/issues/157
In tanstack you can render a row with a custom function. So my thinking was I could push the cards in there. Giving users the ability to toggle between list and card view while keeping the filtering, sorting capabilities tanstack provides.

**Comment by Seltonu** [comment]
That makes sense, pushing the cards into the table sounds like a great way to manage supporting two views in one format. The screenshot from that datatable view looks great too

It seems my feature request is mostly addressed by other tickets independently then - should I go ahead and close this and move any future discussions there, or is it worth keeping this ticket open?

Unfortunately I have no experience with Vue so I can't help out with code at the moment, but happy to stick around for the discussions and any testing!

**Comment by abrittaf** [comment]
Hello, I also have a proposal to improve the search, more precisely the results filter. VueTorrent's interface far surpasses that of qBittorrent, but the latter allows you to use the NOT (**-**) operator when filtering the results, which does not work here. For example one could search for "Die Hard 2" and then in the filter box enter "**-**HDCAM" (and thus eliminate from the results those that contain the word HDCAM). The qBittorrent web interface works like this and I think it is very useful. Thank you and congratulations on the product!
