### ISSUE TITLE
Bring back the "Active" filter

### ISSUE THREAD

**Issue by vtruong68** [VueTorrent/VueTorrent#1280]
In v1.8.0 and previous releases, there was an "Active" status filter. This filter basically showed anything that was currently transferring data (uploading or downloading).
![image](https://github.com/WDaan/VueTorrent/assets/31712352/67a0e057-4574-45bd-a87e-2ab9710d63a3)

Starting with the v2.0.0 release, this doesn't appear to be an option and none of the other options can replicate this feature. Can we please bring this option back?

**Comment by Larsluph** [comment]
It is possible but you'll have to recreate that filter manually. The "Active" filter matches [this rule](https://github.com/qbittorrent/qBittorrent/blob/c88bd7cb3fea5cb52bff8a79953792c6d98615ce/src/base/bittorrent/torrentimpl.cpp#L1044-L1065).

**Comment by vtruong68** [comment]
Ah thanks for pointing that out. I didn't realize filters were multi-select now. It's a mild inconvenience to switch between filters though so I'd still like the active filter to be re-added.
