### ISSUE TITLE
[Feature request] Add option for RSS rules to set the "Seed Limit" for the auto download torrents

### ISSUE THREAD

**Issue by tainewoo** [VueTorrent/VueTorrent#1315]
[Feature request] Add option for RSS rules to set the "Seed Limit" for the auto download torrents

Don't know if this feature need to be implemented by the qbittorrent core API or web UI.
If the WEB UI can achieve this, that would be great.

Currently we can only set the global "Seed Limit" under the qbittorrent option page "Bittorrent", section "Seed Limit".
As that's the global limit, if we only want to keep the global value unchanged, and only set the value for the new torrents that auto added by the RSS rule(s), we will need the option to be implemented in the RSS auto download rule, to set the "Seed Limit" and Behavior after the seed limit reached.

For me, I have thousands of torrents seeding on my qbittorrent, and I will not remove them, I will keep seeding them for years, 7x24.
Besides of these torrents, I also adds some new torrents everyday, auto downloaded by the RSS rule.
I hope I can set the Seed Limit for these auto downloaded torrents by RSS rule. But there is no options available.

![seed_limit](https://github.com/WDaan/VueTorrent/assets/13391232/ef66b124-017a-439a-ad97-9883c255bb41)

**Comment by Larsluph** [comment]
Seems like we can use the same parameters as the AddTorrent dialog in the rules

**Comment by tainewoo** [comment]
cool~
I found there should be ratioLimit and seedingTimeLimit parameter provided by the WEB UI API. But I don't find the parameter to set the operation for the "THEN".

At least, we can use the rule to set the Limit for the new auto downloaded torrents, that would be great too.

===============

<html>
<body>

ratioLimit optional since 2.8.1 | float | Set torrent share ratio limit
-- | -- | --
seedingTimeLimit optional since 2.8.1 | integer | Set torrent seeding time limit. Unit in minutes


</body>
</html>

**Comment by tainewoo** [comment]
And seems that would be better to be provided along with the option:

autoTMM optional | bool | Whether Automatic Torrent Management should be used




</body>
</html>

**Comment by xliamh** [comment]
稳定安全，免费vpn, 支持chatgpt(https://monkeyff02.online/#/portal?c=ad01)

**Comment by tainewoo** [comment]
Can we have this feature soon?  😃 
Without this feature, we have to set the torrents manually, and again and again for the newly added torrents.

Last night I tried to set the old share ratio for seeding torrents as "no limit" using qB 4.5.5 and libtorrent v1.
After upgraded to qB 4.6.1 and libtorrent 2.0.9, the "Inactive time" could be set.
But I forgot to set the seeding torrents as "no limit" again using new qB & libtorrent ( I thought they are "no limit" already).
After I set the global setting for share limit (seed time limit and inactive time limit), qB started to delete my torrents and files.
ah~~~~
I lost 500+ torrents and their files before I reboot the nas for emergency.

At least I saved 1400+ torrents, didn't lose all of them 😃 

I hope we can have this feature soooooon ...

That's the torrents left:
![1455Torrents](https://github.com/WDaan/VueTorrent/assets/13391232/2fab70ae-34e3-43ce-b058-b2ce35ce3d99)

**Comment by tainewoo** [comment]
Hi @Larsluph ,

Is that possible to expose all the torrent parameters to users to set them for each RSS rule?
            "category": 
            "download_limit": 
            "download_path": 
            "inactive_seeding_time_limit": 
            "operating_mode": 
            "ratio_limit": 
            "save_path": 
            "seeding_time_limit": 
            "skip_checking": 
            "stopped": 
            "tags": 
            "upload_limit": 
            "use_auto_tmm":

**Comment by tainewoo** [comment]
Hi @Larsluph , 
Seems we can now implement the feature.
The implementation for setting inactive_seed_time_limit is done from qB side after this PR: https://github.com/qbittorrent/qBittorrent/pull/20231
And this feature is work after qB4.6.3.

Also, refering to this qB issue: https://github.com/qbittorrent/qBittorrent/issues/19944
I tried to modify the download_rules.json to modify the value of inactive_seeding_time_limit, ratio_limit, seeding_time_limit for each rule, by suggestion of jwshields, and find they work find on qB4.6.3.

**Comment by tainewoo** [comment]
One more PR is done to GUI by [glassez](https://github.com/glassez)
https://github.com/qbittorrent/qBittorrent/pull/20324

But it's not available on WEB UI currently.
