### ISSUE TITLE
Import / Export missing after update

### ISSUE THREAD

**Issue by jfgoncalves** [VueTorrent/VueTorrent#1322]
VueTorrent: 2.1.1
qBitTorrent: 4.5.5
Browser: Safari version 17.1 (19616.2.9.11.7)

I can't find the field and buttons to import my settings back. Are they gone?
Tried using another browser on my machine + another one but that area not there anymore. I think I upgraded from a <2.0 version.

**Comment by Beet4** [comment]
A workaround until the feature is back in the Vue3 rewrite is to copy the value of key vuetorrent_webuiSettings in Local Storage of your browser. Hit F12 -> local storage -> your vuetorrent url and find the key.
