### ISSUE TITLE
Setting for Progress Bar Styles

### ISSUE THREAD

**Issue by hl2guide** [VueTorrent/VueTorrent#1324]
Please consider a setting to disable striped progress bars like this:

![example_bar](https://github.com/WDaan/VueTorrent/assets/17044982/168affd2-a8b7-44c0-968d-c6ea86963f2d)

They make it difficult to read the labels (%).

**Comment by tainewoo** [comment]
The progress bar stripping is active for table view while it's disabled for list/grid views.
