### ISSUE TITLE
download path and save path

### ISSUE THREAD

**Issue by billkewl** [VueTorrent/VueTorrent#1372]
Hi.

These two names sound quite confusing and I figured out that they are `Keep incomplete torrents in:` and `Default Save Path ` in original WebUI.
Can you change the names so that it's not as confusing?

and there's a bug in the latest version 2.3.0.
I unchecked `Keep incomplete torrents in:` but it's still enabled by default in add torrent popup.

Also, is there a way to bring add torrent popup foreground as in 1.x version when drag and drop torrents?

Thanks.

**Comment by Larsluph** [comment]
Translation keys edited.

In Add dialog:
- Download path (when incomplete)
- Save path (when completed)

In settings:
- Default Download Path (incomplete torrents)
- Default Save Path

**Comment by Larsluph** [comment]
For the first "bug", it's because the dialog is initialized when adding a torrent and when loading the app. Except in these cases we can't update it automatically to prevent data from being lost when torrents are awaiting upload.

**Comment by billkewl** [comment]
Hi.

Thank you for the update and latest release. There's one more issue with this.

My `"Keep incomplete torrents in" `in original WebUI is unchecked, i.e. I want incomplete .qB files in same directory as complete files, but the `"Download path (when incomplete)"` of VueTorrent UI automatically adds that directory, which is not to be found anywhere in qBittorrent.conf file.
Could you make it empty if `"Keep incomplete torrents in"` in OG UI is unchecked?

Thanks.
