### ISSUE TITLE
Allow list users based on DL speed or UL speed

### ISSUE THREAD

**Issue by xianhongtao** [VueTorrent/VueTorrent#1385]
Which used to be supported is 1.X.0 versions

**Comment by WDaan** [comment]
What do you mean by this? I don't understand this issue.

**Comment by WDaan** [comment]
reopen if still the case.

**Comment by xianhongtao** [comment]
Sort from Fast to Slow

**Comment by Larsluph** [comment]
Right now, they are sorted based on the order received from qBittorrent. We should implement a way to sort, before V2 we used the data table which was doing it by itself but wasn't responsive at all.

**Comment by xianhongtao** [comment]
Thx dude

**Comment by WDaan** [comment]
You can sort by download speed or upload speed? Or are you guys talking about something else?

<img width="551" alt="Screenshot 2024-01-13 at 10 14 35" src="https://github.com/VueTorrent/VueTorrent/assets/25707052/f562f05d-fdd7-4c3b-ac03-9371a4416d7d">

**Comment by xianhongtao** [comment]
in the users interface ,where list all the users connected to you

**Comment by Larsluph** [comment]
Peers tab in Torrent Detail
