### ISSUE TITLE
[Bug] RSS - Rules - Last Match: value is not shown

### ISSUE THREAD

**Issue by tainewoo** [VueTorrent/VueTorrent#1386]
qB: 4.6.2
libtorrent: 2.0.9
VueTorrent: 2.3.0
Browser: Microsoft New Edge

Steps:
1. Brorse to Setting - RSS - Rules, and choose one of the rules that matched recently.
2. Check the value of "Last match". 
3. It's not shown, or maybe because it's "0 day ago?"

![last_match](https://github.com/WDaan/VueTorrent/assets/13391232/ac8bf8b8-6961-4b78-bd10-88190696e508)

**Comment by Larsluph** [comment]
`0 day ago` should show up as "today".
The only case where the data may not be there is because the data is nothing which is weird because this case is handled in the same way as the official WebUI does.

**Comment by tainewoo** [comment]
Hi @Larsluph,
The value of lastMatch:
"lastMatch": "04 Dec 2023 00:51:39 +0000",

Or:
"lastMatch": "01 Dec 2023 09:20:57 +0000",

And I found all rules are not showing the last match value no matter what the lastMatch value is.
