### ISSUE TITLE
[Bug] Speed graph hover gets cut off

### ISSUE THREAD

**Issue by LeaderbotX400** [VueTorrent/VueTorrent#1389]
![image](https://github.com/WDaan/VueTorrent/assets/34589843/897ca489-0b1d-4339-885b-73590ad66749)

**Comment by WDaan** [comment]
Can't seem to reproduce this

**Comment by temhelk** [comment]
Is this the same issue or not? After the arrival of the new data in the graph window the hover circle dissapears and I cannot get the values for the download (~or just the top?~, checked, it seems I only see the upload) line.

I'm experiencing that on clean Firefox 151.0.4 on Windows, while chrome and edge seem to handle that correctly.

https://github.com/user-attachments/assets/498e985a-baea-4f7b-9c36-ec106c324787
