### ISSUE TITLE
Spacer in torrent card

### ISSUE THREAD

**Issue by Lokilicious** [VueTorrent/VueTorrent#1393]
Would it be possible to add the possibility to add horizontal spacers in the torrent card?

**Comment by Lokilicious** [comment]
in the main torrent overview

**Comment by WDaan** [comment]
Could you perhaps give a screenshot and draw where you'd like to have a spacer?

**Comment by Lokilicious** [comment]
Attached a screenshot, ideally though the position of the spacer could be changed. End result should be that the stuff after the spacer is right aligned, while the stuff before it stays left aligned.

![Screenshot 2024-01-15 at 13 53 22](https://github.com/VueTorrent/VueTorrent/assets/15230279/8428aa93-15a6-4eb0-87bf-ab6bfff8ab87)

**Comment by Larsluph** [comment]
It looks like a really custom need, why not use the table view in that case?

**Comment by Lokilicious** [comment]
What’s the table view? 😂
