### ISSUE TITLE
Scrollbar Styling Issue on PC Chrome

### ISSUE THREAD

**Issue by CharlesLTH** [VueTorrent/VueTorrent#1397]
I've encountered an issue with the scrollbar in the sidebar of the PC webpage after upgrading from version 1.8.0 to 2.0.x. Below are the details:

**Browsers Tested:**
Chrome 120.0.6099.71
Cent Browser Chromium 102.0.5005.167

**Issue Description:**
After the upgrade (versions tried: 2.0.1 and 2.3.0), the sidebar's scrollbar lost its custom styling and reverted to a basic gray rectangle. This was not a problem in the earlier version 1.8.0.

**Additional Information:**
I also tested the same on the Safari browser on an iPhone, the scrollbar in version 2.0.x appears to be functioning normally there.

![1](https://github.com/WDaan/VueTorrent/assets/33312999/32343768-eb6e-4c42-9fdc-9e787de44f8c)

**Comment by nikeshpurohit** [comment]
Can confirm, having the same issue

**Comment by kotlyne** [comment]
Same issue on version 2.4.0

**Comment by CharlesLTH** [comment]
> Can someone include a screenshot of the previous styling? I don't remember having a custom styling on that before.

These are the old style:

<img width="1081" alt="vue_1 8 0_2" src="https://github.com/WDaan/VueTorrent/assets/33312999/27d3bd7b-9dfb-4ef8-8cd0-4bb2b32e64fb">

<img width="1084" alt="vue_1 8 0_1" src="https://github.com/WDaan/VueTorrent/assets/33312999/bc0eed74-d36a-42b9-aa6b-c6a05515e938">

**Comment by Larsluph** [comment]
Thanks 😄 I never noticed that it was done before, sorry for the inconvenience, will fix asap.
