### ISSUE TITLE
Icons do not display until I clear cache

### ISSUE THREAD

**Issue by jsaltzman** [VueTorrent/VueTorrent#1407]
On Vuetorrent none of the icons (select, search, add, etc) display until I clear my cache. Once I clear my cache, the icons will come back for a day or two, until disappearing again (requiring another cache clear).

<img width="1534" alt="image" src="https://github.com/WDaan/VueTorrent/assets/2000982/106c67cb-189a-4299-811a-01060f2e58fe">

**Comment by WDaan** [comment]
https://github.com/VueTorrent/VueTorrent/issues/1447

Ran into this as well, got resolved... not sure what changed yet. Thanks for reporting.
