### ISSUE TITLE
Priority get/set on individual files not working

### ISSUE THREAD

**Issue by FlawTECH** [VueTorrent/VueTorrent#1411]
Currently using v2.4.0

I have an issue where individual file priority is not showing up in the contents of a torrent.
When I set the priority, nothing happens, and I see an error on the request to `<qbitUrl>/api/v2/torrents/filePrio` which responds with `File IDs must be integers`.

![image](https://github.com/WDaan/VueTorrent/assets/36300135/ead394ca-4132-4190-970d-623251245faf)

I'm guessing this has probably to do with an API update from qBittorrent. I'm currently running qbittorrent-nox 4.2.5-0.1 on Debian 11

**Comment by Larsluph** [comment]
That's weird, looking at the API nothing has changed since then. Could you send an extract of the payload?

**Comment by FlawTECH** [comment]
Hi,
Here is one of these requests:
![image](https://github.com/WDaan/VueTorrent/assets/36300135/0875f06f-344e-4c66-ab68-98409e5ca9ff)

This is when using the normal UI:
![image](https://github.com/WDaan/VueTorrent/assets/36300135/6ac8b982-7518-4fbb-ae0d-b53df3315492)

It seems that, for some reason, the id is undefined. It does that for every file.
I see no other errors in console or network panel prior to that. It seems the priority is missing on files when loading the content tab though (see screenshot in original post).

**Comment by Larsluph** [comment]
Thanks for the feedback, will take a look while reworking the view.
