### ISSUE TITLE
Logs on log screen are unreadable.

### ISSUE THREAD

**Issue by GRobecchi** [VueTorrent/VueTorrent#1420]
Whenever a log exceeds the screen width it is impossible to read the full content, as neither does the text wrap, nor the page scroll, nor is it possible to inspect the log by clicking on it.

This means that to inspect a log properly one must disable the interface altogether first, then enable it again once the contents have been inspected. 

This is not an efficient workflow.

If keeping the screen compact is a concern, I would recommend a "tap to expand" approach to this.

**Comment by tainewoo** [comment]
Currently I achieve this by the feature of the browser: zoom out.
