### ISSUE TITLE
[Feature Request]: Allow selection of Content folders

### ISSUE THREAD

**Issue by bilogic** [VueTorrent/VueTorrent#1432]
### Description

Sometimes I only want to download 1 or 2 files from a very big torrent

### Describe the solution you'd like

I like to have a bulk action button to make all files/content unwanted

### Describe alternatives you've considered

Select each file 1 by 1 as unwanted, very painful because big torrents can have thousands of files

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Anteus** [comment]
Select/unselect all files and also per folder like the default WebUI would be nice

**Comment by WDaan** [comment]
Most of these content related issues are all blocked by [this](https://github.com/vuetifyjs/vuetify/issues/13518).
The component is not yet available.

**Comment by rooty0** [comment]
@WDaan just curious, is this will be implemented as a part of https://github.com/vuetifyjs/vuetify/issues/13518
