### ISSUE TITLE
Bug: missing icons

### ISSUE THREAD

**Issue by WDaan** [VueTorrent/VueTorrent#1447]
Icons missing since last couple versions

**Comment by Larsluph** [comment]
wdym by that ? Like every mdi icons ?

I know sometimes cache makes it render with weird symbols instead of real icons.

**Comment by WDaan** [comment]
Exactly that. Usually they appear upon a reopen but not it doesn't seem to be resolving itself.


![image](https://github.com/WDaan/VueTorrent/assets/25707052/46cc66a9-b1de-40ce-ae21-868abc182683)

**Comment by gianlucalauro** [comment]
When this happens to me I press the key combination ctrl + shift + r to reload the page and clearing the cache

**Comment by WDaan** [comment]
Seems to be resolved, idk what changed.
