### ISSUE TITLE
[Bug]: Copy context menu does not work

### ISSUE THREAD

**Issue by maxiwheat** [VueTorrent/VueTorrent#1448]
### Bug description

If I right-click on a torrent in list mode and select Copy > Name (or hash or magnet) it does not work, nothing gets in my clipboard.

### Expectations

Copy the information in my clipboard

### Relevant debug informations

```shell
I didn't really test the nightly build, I don't know how.
```

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type and name: Desktop computer
OS: Windows 10
Browser: Chrome 120.0.6099.200

PWA: ?
Running inside a container: Yes
```

### qBittorrent version

4.6.2

### VueTorrent version

2.4.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by WDaan** [comment]
Are you running in a non-https environment? 🤔

Which browser?

**Comment by maxiwheat** [comment]
Yes it's non-https

**Comment by WDaan** [comment]
Same as #1414

**Comment by maxiwheat** [comment]
> Same as #1414

Yeah, I forgot the remove the “open” status from my search before posting #facepalm

But I like the idea that it should somewhat be clear that the feature is disabled (have tooltip or something) because it is not https. Now that is disappointing because you think it would work because nothing is showing, but it just won’t copy silently. Also, it is not possible to select the text with the mouse in the interface, so no real fallback to copy the name of a torrent there.

**Comment by WDaan** [comment]
You should be able to copy info from the information dialog. 

But I still agree that this should be shown a bit more clearly

**Comment by Larsluph** [comment]
This is really weird because you should see a toast indicating that the copy didn't happen

**Comment by maxiwheat** [comment]
> This is really weird because you should see a toast indicating that the copy didn't happen

I don't know what you mean by a toast, but I tried again to see if I missed something, but no, nothing happens.

I opened the Chrome Dev console and this is what is displayed when I click on "Copy"

![image](https://github.com/WDaan/VueTorrent/assets/1927334/9aa56842-f7da-4efa-8725-ea18477af383)

**Comment by Larsluph** [comment]
writeText is what is used when clipboard is available, the app should check before, it must be missing somewhere 🤔
