### ISSUE TITLE
[Feature Request]: Ability to skip multiple files by selecting a folder

### ISSUE THREAD

**Issue by rooty0** [VueTorrent/VueTorrent#1453]
### Description

Greetings,

How hard is it to implement a feature to be able to click on a folder within torrent content to skip all files in the folder?

(Same way as it's implemented in qBittorrent GUI and the default webui)
![select_pre](https://github.com/VueTorrent/VueTorrent/assets/6276644/ba35b059-e2e3-4075-b97f-ea06c8e51cc9)

Sometimes, I have a torrent with content of like 8 folders, 10 files per folder, and it's super annoying to go over/click every single file to skip it because actually a single folder is all what you need.

### Complementary informations

- [X] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
Duplicate of #1432
