### ISSUE TITLE
Bug/Feature/Improvement: Content Tab

### ISSUE THREAD

**Issue by WDaan** [VueTorrent/VueTorrent#1456]
# Description

There are a lot of ergonomic improvements that could be made to the content panel, however we're waiting for [this](https://github.com/vuetifyjs/vuetify/issues/13518) component to become available

Grouping all Content related issues:
- #1432 
- #1363
- #1174
- #1173
- #1115
- #894 
- #1411
- #1019

**Comment by Larsluph** [comment]
Currently working on something, it takes time to design the view to allow all those features in a single UI

**Comment by cybersholt** [comment]
@Larsluph do you need any help testing this or anything in the future? Same to @WDaan, this is an awesome project and would love to help.

**Comment by Larsluph** [comment]
I could probably use some help on the design. That's the only pain point that slows me down actually.

Apart from that, you could plug your qbit instance to the nightly branch to test out features before the official release. It would really help a lot.

Don't hesitate to reach us on the discord to let us know if you encounter some weird things or even better, to let us know that new stuff works fine!

**Comment by cybersholt** [comment]
Awesome Lars, I've got my instance swapped over to the nightly and built that and joined you all over on discord too.
