### ISSUE TITLE
[Feature Request]: Add difference between downloaded and uploaded

### ISSUE THREAD

**Issue by landaisbenj** [VueTorrent/VueTorrent#1457]
### Description

Hello, can i ask if it possible to make another option on side bar to add the difference between downloaded and uploaded ? This could give us the possibility to see the downloadable quantity to stay on positive ratio

### Describe the solution you'd like

Maybe like ratio or free space : 
![image](https://github.com/VueTorrent/VueTorrent/assets/32144431/14e078d0-40ac-4b91-9312-ff78336da0ca)

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by WDaan** [comment]
Isn't this exactly what ratio means? 🤔
It would show you the amount of GB you'd need to upload/download but not sure if that's usefull enough to build into an actual feature.
