### ISSUE TITLE
iOS 14 support 

### ISSUE THREAD

**Issue by Landxhent** [VueTorrent/VueTorrent#1462]
### Description

Vuetorrent does not support IOS 14.

IPhone 12mini ios 14.1 
Qbittorrent 4.6.2
Vuetorrent 2.5.0

Attempt to open web ui with vuetorrent installed results in blank page.

Inspecting it with devtools shows that javascript is not enabled, though it is.

Checked on the same device with cyberkit (newer ios webkit for outdated OS) - everything runs ok

Seems like ios 14 safari is not enough to run vuetorrent.

![A07677C3-DD9A-4076-AA8A-90C9F81759A8](https://github.com/VueTorrent/VueTorrent/assets/78101742/25c62e6a-aa87-4c70-8fd1-1c489c87639e)
![5A98CD51-7674-40B3-A99C-9182CA262D42](https://github.com/VueTorrent/VueTorrent/assets/78101742/5ae13eb5-c6a3-4d95-a9f4-2661cfabdf43)

### Describe alternatives you've considered

If it's possible, disable some features which require more updated javascript for ios14

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Landxhent** [comment]
As a temporary (or the only) solution - found that vuetorrent version 1.1 is the last version that launches on ios 14.  

Seems like features added in version 1.2 breaks it

** 1.2.0 (2023-01-11)

Features

Add globalSpeed and globalVolume computed values to torrent properties (#599) @Larsluph (3e1d341)
add pending pieces color to canvas (#592) @Larsluph (5132d4d)
Add support for "autorun on torrent added" option (#580) @Larsluph (19bf989)
Add/Ban peers support (#598) @Larsluph (59b47db)
Bug Fixes

"409 Conflict" on file/folder rename (#597) (004c8f5)
Dashboard items not using $store.state reference (#601) (add11c9)
Default change location not prefilling (#583) @Larsluph (b53c331)
Improvements

Add "Completed On" to dashboard customization settings (#578) (02db288)
Add scroll support in TorrentRightClickMenu (#589) @Larsluph (cd2f764)
Add toast when renameFile and renameFolder returns 409 Conflict (#588) @Larsluph (e01d9a0)
improve russian translations (#593) @Balya (684690a)
reset pageNumber when changing filters to prevent value overflow (#591) @Larsluph (719c5e9)**

**Comment by WDaan** [comment]
iOS 14 is no longer under active support. 

Not sure if backporting is worth it.
