### ISSUE TITLE
[Feature Request]: Filter by Tracker on Left Sidebar

### ISSUE THREAD

**Issue by Pentaphon** [VueTorrent/VueTorrent#1472]
### Description

I'd like to filter by Tracker on Left Sidebar. I want to only see torrents from a certain tracker sometimes, just like in the desktop qBittorrent client. 

### Complementary informations

- [X] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
There's an option in the settings to enable it.
