### ISSUE TITLE
Dark mode icon doesn't work until Dark mode selected once in settings.

### ISSUE THREAD

**Issue by kevinmarchant** [VueTorrent/VueTorrent#1478]
### Bug description

On my system the Dark/Light mode toggle button on the "Side bar" was greyed out.  

If you go into Vuetorrent settings (cog wheel icon in top right) and scroll down to Vuetorrent theme at the bottom, you can set it to dark mode and save the settings using the disk icon. After you've set it once in the settings the button on the man screen (little sun icon) starts to work properly.

You can recreate the issue by using a Chrome Incognito window i.e. seems to be a problem on Vuetorrent first use  / initialisation of setting for dark/light mode in Sidebar.

### Expectations

Dark/Light mode toggle button on the "Side bar" should be available at first use of Vuetorrent and not require using Settings to initialise the mode.

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type and name: 
OS: iOS 17 Safari and Chrome 120.0.6099.225 on Windows 10 x64

PWA: No
Running inside a container: No
```

### qBittorrent version

4.5.5

### VueTorrent version

2.5.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by Larsluph** [comment]
This is not a bug, it's an intended behaviour.

The icon is disabled because the default is to follow the system theme.

**Comment by kevinmarchant** [comment]
OK thanks.  On my iPhone and iPad both running iOS 17 and set to dark mode Vuetorrent is in light mode by default which is why I was confused.  Same for my Windows system, so perhaps the problem is it's not picking up the system default properly ?

Might it be more intuitive for the button to be set to "Auto/Follow" on first launch and be a three way button (light/dark/auto).  Didn't find having to go into settings intuitive - I was driven to post this as there was a similar post on Reddit [https://www.reddit.com/r/qBittorrent/comments/16yb9z5/how_do_i_enable_dark_mode_with_qbittorrent_and/](url)

Thanks for the quick reply anyway.

**Comment by cybersholt** [comment]
Additionally, it's important to highlight that privacy-centric browsers such as Brave prioritize user privacy by not disclosing the user's dark mode preferences. This approach is part of their comprehensive efforts to curb [fingerprinting](https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections), ensuring a more private and secure browsing experience.

**Comment by Larsluph** [comment]
> privacy-centric browsers prioritize user privacy by not disclosing the user's dark mode preferences

Really interesting! I wasn't aware of that
