### ISSUE TITLE
[Bug]: sub-menus are broken on latest commits

### ISSUE THREAD

**Issue by soredake** [VueTorrent/VueTorrent#1483]
### Bug description

https://github.com/VueTorrent/VueTorrent/assets/5204968/aceee6fd-d769-49b8-85d4-afdd36001bfc

### Expectations

Sub-menus should work fine, as they do on 2.5.0

### Relevant debug informations

```shell
Tested on latest edge and firefox on windows.
```

### How did you install VueTorrent?

Built from source

### Environment description

```plain text
Device type and name: PC
OS: Windows 11 Pro

PWA: No
Running inside a container: Yes
```

### qBittorrent version

4.6.3

### VueTorrent version

2.5.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by Larsluph** [comment]
Already fixed with #1471

**Comment by Larsluph** [comment]
Well looks like the latest dependabot PR broke it again, will take a look before the next release

**Comment by Larsluph** [comment]
> @Larsluph apologies... forgot to check that

No worries! That's the problem of not having a consistent test suite 😞
