### ISSUE TITLE
[Bug]: Error "Prividing settings is required" when trying to import settings

### ISSUE THREAD

**Issue by tainewoo** [VueTorrent/VueTorrent#1493]
### Bug description

Error "Prividing settings is required" when trying to import settings.
Steps:
1. upgrade to VueTorrent 2.6.0.
2. Open settings -> Export Settings
3. Save the generated settings.json to local.
4. Open the settings.json and copy the content of it.
5. Open settings -> Import Settings.
6. Paste the content to the imput field of the "Import Settings".
7. Error msg shows, and the "Save" button is not active, the settings can't be imported.

![importsettings](https://github.com/VueTorrent/VueTorrent/assets/13391232/a60ac146-639f-4f5d-aea5-44e68ecf94fb)

### Expectations

The settings can be imported.

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type and name: 
OS: Win11

PWA: No
Running inside a container: No

Browser: Microsoft New Edge
```

### qBittorrent version

4.6.3

### VueTorrent version

2.6.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by WDaan** [comment]
Thanks for the feedback, it's probably the validation rule that's a bit too naive.
