### ISSUE TITLE
[Bug]: Webui always asks for username/password

### ISSUE THREAD

**Issue by kraM1tt** [VueTorrent/VueTorrent#1502]
### Bug description

Even if I've only just closed the tab, it asks me to login again. Using default webui it never asks me to login as I've whitelisted my PC IP address and subnet. Older versions of VueTorrent worked, but I don't know which, currently using latest.

### Expectations

To stay logged in.

### How did you install VueTorrent?

Fetched from latest-release branch

### Environment description

```plain text
Device type and name: 
OS: Win !0

PWA: 
Running inside a container: No
```

### qBittorrent version

4.6.3

### VueTorrent version

2.6.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by Larsluph** [comment]
When opening the WebUI, a request is made to detect the current login state (authentication is cookie-based).

The login screen shows up if this request fails.

Open up the DevTools on a desktop (using F12) and go to the Network tab. You should find a request named "buildInfo" in the list. Could you please tell us the status code of that request?

**Comment by kraM1tt** [comment]
![image](https://github.com/VueTorrent/VueTorrent/assets/89113987/2b6cbde6-49b3-4115-a2c3-3c3c96230a8b)

Hopefully this is correct?

**Comment by Larsluph** [comment]
The list is empty, try clearing your filters (the red funnel icon at the top)

**Comment by kraM1tt** [comment]
Hmmm I cleared the filters like you said and it still seems the same

![image](https://github.com/VueTorrent/VueTorrent/assets/89113987/3a6a0ce1-5852-4302-9158-8ecc9980f457)


Any idea?

**Comment by kraM1tt** [comment]
To be clear I'm trying to access qbit web that's on another PC on the network. If I run the test from the localhost PC it still asks to login every time but I seem to get proper logs for you

![image](https://github.com/VueTorrent/VueTorrent/assets/89113987/c399f899-a9e8-482e-a462-f67d639b87ff)

**Comment by Larsluph** [comment]
That's it!
The weird thing is that you receive some 404 on the buildInfo route. That's unusual 🤔, I didn't even know it was possible...

**Comment by Larsluph** [comment]
Is it still happening?
@kraM1tt @parasiteoflife

**Comment by kraM1tt** [comment]
It is unfortunately but now it's also doing it with default webui so I have no clue what's going on lol

**Comment by Larsluph** [comment]
In that case I'm not sure if we should keep it open...
@WDaan what do you think?

**Comment by hron** [comment]
This one happens to me as well in Firefox on Android. I have just tried to access qbittorrent via Brave Browser and it works without asking the login/password every time. My setup uses a self-signed certificate. Just FYI

**Comment by OsaPL** [comment]
Even tho it keeps asking for login, even if I type wrong user/password, on clicking login it just remembers, and logs you in anyways.
Behaves the same way for me from other devices. I'm on 3.80, qbittorrent 4.1.7

`/api/v2/app/buildInfo` returns 404.

**Comment by Larsluph** [comment]
> I'm on 3.80, qbittorrent 4.1.7
> 
> `/api/v2/app/buildInfo` returns 404.

This 404 is normal, the `buildInfo` route has been added in 2.3.0. We definitely need to find a reliable way to check authentication status.

**Comment by Larsluph** [comment]
Outdated
