### ISSUE TITLE
[Bug]: Can’t adjust file priority on mobile

### ISSUE THREAD

**Issue by DaveAlton** [VueTorrent/VueTorrent#1503]
### Bug description

When viewing the new content page, on smaller screens, the priority and rename buttons disappear entirely. 

### Expectations

I expect a button for priority and renaming. I can see them on desktop. 

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type and name: 
OS: Docker

PWA: Yes 
Running inside a container: Yes
```

### qBittorrent version

4.6.3

### VueTorrent version

2.6.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist in

**Comment by Larsluph** [comment]
These actions have been moved to a right click menu, try holding your finger on a file to display it.

**Comment by DaveAlton** [comment]
I tried that. It just selects text. Tapping with two fingers does nothing either.

**Comment by DaveAlton** [comment]
Another issue is that, on the second time viewing the content page (exit and go back to a torrent's content), it appears like this. Pressing the X to exit freezes the page and you have to reload the whole page. 

![image](https://github.com/VueTorrent/VueTorrent/assets/4853190/5b3f43fc-6d02-445f-bda4-3aa3561d71cd)

Overall, I love the new layout, but it'll be better with a couple bug fixes.

**Comment by Larsluph** [comment]
I just tried it on my android phone and it works fine.

Are you using an iPhone by any chance? I know we already had a lot of trouble supporting the right click on Apple devices...

**Comment by DaveAlton** [comment]
Yes

**Comment by Magrid0** [comment]
i'm having the same problems, i also have an iphone
