### ISSUE TITLE
[Bug]: Text value of some new added dialogs.add.params fields for RSS rules are missed

### ISSUE THREAD

**Issue by tainewoo** [VueTorrent/VueTorrent#1526]
### Bug description

The text value of some new added dialogs.add.params fields for RSS rules are missed.
These fields are new implemented since VueTorrent 2.7.0.
Seems the text values are not defined.

### Expectations

There should be field name for the parameters displayed, not the code names.

### Steps to reproduce

1. Upgrade VueTorrent to the latest v2.7.0 release
2. Browser to Options - RSS - Rules.
3. Edit one of the RSS rules, and click on the "DIALOGS.ADD.PARAMS.TITLE".

![text_not_defined_1](https://github.com/VueTorrent/VueTorrent/assets/13391232/42e65f5e-26c6-4be0-a9d0-0fe1b9439139)

![text_not_defined_2](https://github.com/VueTorrent/VueTorrent/assets/13391232/f145bb6f-766d-4ec1-8d1f-d9f253acd7fa)

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type and name: PC
OS: Win 11

PWA: No
Running inside a container: No
```

### qBittorrent version

4.6.3

### VueTorrent version

2.7.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by Larsluph** [comment]
This has already been fixed. Don't forget to check nightly before sending a bug report...
