### ISSUE TITLE
[Bug]: when accessed by https, login page is entirely error, can't login. but http can access properly. 

### ISSUE THREAD

**Issue by a1156883061** [VueTorrent/VueTorrent#1534]
### Bug description

![image](https://github.com/VueTorrent/VueTorrent/assets/36263893/10650653-a581-4fad-84cc-aa8374ace946)
login page 

And below is error log.
![image](https://github.com/VueTorrent/VueTorrent/assets/36263893/84d05e99-f20d-49fa-b412-6cfa1fcee5b8)

![image](https://github.com/VueTorrent/VueTorrent/assets/36263893/a29465b2-b676-4845-8a4c-55ff8c8898ea)
http can access properly.

### Expectations

login page show correctly.

### Relevant debug informations

```shell
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' http: https: ws: wss: data: blob: 'unsafe-inline'".

    at new Function (<anonymous>)
    at My (vue-tp2yrxEM.js:39:8721)
    at zd (vue-tp2yrxEM.js:39:10705)
    at Xc (vue-tp2yrxEM.js:39:9774)
    at vue-tp2yrxEM.js:43:4954
    at Re (vue-tp2yrxEM.js:43:4675)
    at Proxy.Ne (vue-tp2yrxEM.js:43:4940)
    at index-BxCS0EpI.js:9:365294
    at Object.r [as default] (vue-tp2yrxEM.js:13:4785)
    at default (index-BxCS0EpI.js:9:165378)
```

### Steps to reproduce

1. just access login page

### How did you install VueTorrent?

Using a third-party docker image (hotio or others)

### Environment description

```plain text
Device type and name: laptop-
OS: Linux version 5.15.0-91-generic (buildd@lcy02-amd64-061) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #101~20.04.1-Ubuntu SMP Thu Nov 16 14:22:28 UTC 2023

PWA: No
Running inside a container: Yes
The SSL certificate file is config in nginx and proxy pass to qBittorrent.
```

### qBittorrent version

4.6.3

### VueTorrent version

2.7.0

### Agreements

- [X] The bug still occurs on the nightly build
- [x] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by Larsluph** [comment]
Given that you don't use direct access, this bug may come from your nginx / proxy configuration. Try editing your CSP to match qBittorrent's.

cf https://stackoverflow.com/a/72377323/12717385

**Comment by a1156883061** [comment]
> Given that you don't use direct access, this bug may come from your nginx / proxy configuration. Try editing your CSP to match qBittorrent's.
> 
> cf https://stackoverflow.com/a/72377323/12717385

Thanks!
