### ISSUE TITLE
[Feature Request]: Add torrent params for monitored folders

### ISSUE THREAD

**Issue by SFTP65535** [VueTorrent/VueTorrent#1540]
### Description

When adding a new Monitored folder, allow for greater customization, like the standalone GUI application. Currently, WebUI users can only edit these settings manually through the watched_folders.json file inside the qBittorrent config folder.

### Describe the solution you'd like

Adding the same options that are presented in the GUI application, such as categories, starting torrents automatically or not and torrent management mode, etc. It would make the feature itself more useful for handling big amounts of torrents.

![image_2024-02-23_17-47-00](https://github.com/VueTorrent/VueTorrent/assets/148251773/de1bfaaf-db59-4204-9522-9d69081d2921)

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
The feature isn't implemented in both VueTorrent and the native WebUI because the current API doesn't allow to do so.

[source](https://github.com/qbittorrent/qBittorrent/blob/master/src/webui/api/appcontroller.cpp#L563-L611)

**Comment by SFTP65535** [comment]
> The feature isn't implemented in both VueTorrent and the native WebUI because the current API doesn't allow to do so.
> To edit those settings, you'll have to edit the `watched_folders.json` file manually until the API is updated.
> 
> [source](https://github.com/qbittorrent/qBittorrent/blob/master/src/webui/api/appcontroller.cpp#L563-L611)

Makes sense. So that's why the native WebUI doesn't have it either.
