### ISSUE TITLE
[Bug]: Proxy type not showing or saving properly

### ISSUE THREAD

**Issue by ozguncagri** [VueTorrent/VueTorrent#1559]
### Bug description

Changing proxy type from default web UI works as expected but changing it from vue torrent not saving it properly. And it also shows type as numbers. Probably it's type option's index numbers because if I select SOCKS5 it shows 2 which is third option on default web ui.

Here is how same setting is shown differently on each ui;

![image](https://github.com/VueTorrent/VueTorrent/assets/946294/4f2ba35c-fe3e-44a5-9d2e-da0ae60be276)

![image](https://github.com/VueTorrent/VueTorrent/assets/946294/caa69ea8-31b9-4e02-ad71-822c92827067)

### Expectations

It has to save selected option but instead it saves as none

### Steps to reproduce

1. Change proxy type on default web ui
2. Switch to vue torrent ui

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type and name: 
OS: Docker

PWA: No
Running inside a container: Yes
```

### qBittorrent version

4.4.1

### VueTorrent version

2.7.1

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by Larsluph** [comment]
This settings has changed format since 4.6.0. It was previously an integer, now it's a string.

Please read the agreements before ticking them.

**Comment by ozguncagri** [comment]
Sorry my bad. Package is not the latest version on ubuntu's repos.
