### ISSUE TITLE
[Wiki]: Systemd Unit Improvements

### ISSUE THREAD

**Issue by chadsr** [VueTorrent/VueTorrent#1560]
### Description

Firstly, thanks for your work!

I noticed that the [example systemd unit](https://github.com/VueTorrent/VueTorrent/wiki/Keeping-VueTorrent-up%E2%80%90to%E2%80%90date-automatically#using-systemd) for keeping VueTorrent updated could be expanded to prevent potential edge-case issues such as no network connection, or starting when the system isn't ready.

I've attached an expanded version in-case you're interested in updating the example. This version also stops systemd from complaining about the lack of `WantedBy` (etc...) when enabling the unit.

### Describe the solution you'd like

Might I suggest expanding the `update-vuetorrent.service` unit example with the following:
```
[Unit]
Description=Keep VueTorrent up-to-date service
Wants=network-online.target
After=network-online.target nss-lookup.target

[Service]
Type=simple
User=larsluph  # Replace with the owner user
Group=users    # Replace with the owner group
WorkingDirectory=/path/to/vuetorrent # Replace with path to local VueTorrent git repository
ExecStart=git pull

[Install]
WantedBy=multi-user.target
```

- `Wants=network-online.target` / `After=network-online.target nss-lookup.target`
   Will make sure the unit always waits for network/dns to be active before starting
- `WorkingDirectory`
   Just a personal opinion, but to me this is cleaner / safer than using `git -C` 
- `WantedBy=multi-user.target`
  Indicates that the system is ready for user sessions

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by WDaan** [comment]
Updated :D
