### ISSUE TITLE
[Bug]: vuetorrent shows Blank screen on older versions of Android devices (starting from 2.5.0)

### ISSUE THREAD

**Issue by momokoudai** [VueTorrent/VueTorrent#1561]
### Bug description

When I upgraded the vuetorrent from the old version to the latest version, the browser started to be white screen, but the display on the computer was normal.

 I downloaded the source code from GitHub for version by version analysis, and finally found that this problem began from 2.5.0.

 After analysis, I found that the problem is in the` src\services\index.ts` file.

`const qbit = await getProvider()` When I delete the `await`, it appears normally.

 My mobile browser ua is `Mozilla / 5.0 (Linux; U; Android 11; zh-cn; Redmi K20 Pro Build / RKQ 1.200826.002) AppleWebKit / 537.36 (KHTML, like Gecko) Version/4.0 Chrome/79.0.3945.147 Mobile Safari/537.36 XiaoMi/MiuiBrowser/14.3.21`
It is normal when I use the latest `edge (chrome / 122.0.0.0, android version)`.

 I guess maybe using `await` at the top level caused the older version of the browser not supported.

 I hope that this problem can be fixed.

 thanks.

### Expectations

It works work on the older version of the browser

### Steps to reproduce

1. Deploy vuetorent with version number greater than 2.5.0 
2. Accessing Vuetorent with an older browser
...

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type and name: 
OS:  Redmi K20 Pro Build / RKQ 1.200826.002

PWA: Yes / No
Running inside a container: Yes / No

I deploy on qbittorrent or simply use `npm run dev` to run vuetorrent
```

### qBittorrent version

4.6.3

### VueTorrent version

2.5.0+

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by momokoudai** [comment]
I found a solution：
`npm install vite-plugin-top-level-await -D
`
edit vite.config.js
`import topLevelAwait from 'vite-plugin-top-level-await'
`
`plugins: [
    topLevelAwait({
      promiseExportName: '__tla',
      promiseImportName: i => `__tla_${i}`
    })
  ],
`
`npm run build`

**Comment by Larsluph** [comment]
Great! Can you open a PR for that fix?
