### ISSUE TITLE
[Feature Request]: different colors for ratio-values 

### ISSUE THREAD

**Issue by labdiynez** [VueTorrent/VueTorrent#1562]
### Description

different colors for ratio-values 

![image](https://github.com/VueTorrent/VueTorrent/assets/52117480/24fe0219-f597-4fb4-a5ed-541d4f7dcda5)

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
Looks great!
Can you include the threshold you'd like to see for those colours, both the colour and the associated ratio values.

**Comment by labdiynez** [comment]
> Looks great! Can you include the threshold you'd like to see for those colours, both the colour and the associated ratio values?

I can't tell you the criteria, but the examples are from:

[](https://github.com/CallMeBruce/nightwalker)
