### ISSUE TITLE
[Bug]: seeding_time_limit becomes "-2" if using the webui to modify the Seeding time limit for RSS Rule

### ISSUE THREAD

**Issue by tainewoo** [VueTorrent/VueTorrent#1571]
### Bug description

seeding_time_limit becomes "-2" if using the webui to modify the Seeding time limit for RSS Rule.

### Expectations

It should be the value user set for it.

### Relevant debug informations

`setRule` payload:

```json
{
  "affectedFeeds": [],
  "enabled": false,
  "episodeFilter": "",
  "ignoreDays": 1,
  "lastMatch": "25+Sep+2023+10:58:04++0000",
  "mustContain": "-xxBtsHD|-xxBtsTV|-Zone",
  "mustNotContain": "\\[\\d*\\.\\d*+MB\\]|\\[[0-5]\\.\\d*+GB\\]|\\[[3-9]\\d\\.\\d*+GB\\]|[1-9]\\d\\d\\.\\d*+GB\\]|\\[\\d*\\.\\d*+TB\\]",
  "name": "BTSCHOOL",
  "priority": 0,
  "smartFilter": false,
  "useRegex": true,
  "previouslyMatchedEpisodes": [],
  "torrentParams": {
    "category": "Temp",
    "download_limit": -1,
    "download_path": "",
    "inactive_seeding_time_limit": 90,
    "operating_mode": "AutoManaged",
    "ratio_limit": -1,
    "save_path": "/volume3/T3/PT/UploadOnly",
    "seeding_time_limit": "2160",
    "skip_checking": false,
    "stopped": false,
    "tags": [
      "BTSCHOOL"
    ],
    "upload_limit": -1,
    "use_auto_tmm": false
  },
  "addPaused": false,
  "assignedCategory": "Temp",
  "savePath": "/volume3/T3/PT/UploadOnly",
  "torrentContentLayout": null
}
```

### Steps to reproduce

1. upgraded to lastest or nightly release.
2. Browse to qB settings, RSS, Rules
3. Click on one of the rules, and click on the "TORRENT PARAMETERS"
4. input a value of the "Seeding time limit", such as, 2160.
5. Close the TORRENT PARAMETERS, and "Save" the settings of the rule.
6. Click on t he rule agan, and click on the "TORRENT PARAMETERS" again, and check the saved value of the "Seeding time limit", it's "-2" (It should be "2160").

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type and name: PC, Synology NAS
OS: Win11

PWA: No
Running inside a container: No
```

### qBittorrent version

4.6.3

### VueTorrent version

2.7.1

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by Larsluph** [comment]
Please include the associated `setRule` request from DevTools' "Network" tab.

**Comment by tainewoo** [comment]
the request value should be normal:

{"affectedFeeds":[],"enabled":false,"episodeFilter":"","ignoreDays":1,"lastMatch":"25+Sep+2023+10:58:04++0000","mustContain":"-xxBtsHD|-xxBtsTV|-Zone","mustNotContain":"\\[\\d*\\.\\d*+MB\\]|\\[[0-5]\\.\\d*+GB\\]|\\[[3-9]\\d\\.\\d*+GB\\]|[1-9]\\d\\d\\.\\d*+GB\\]|\\[\\d*\\.\\d*+TB\\]","name":"BTSCHOOL","priority":0,"smartFilter":false,"useRegex":true,"previouslyMatchedEpisodes":[],"torrentParams":{"category":"Temp","download_limit":-1,"download_path":"","inactive_seeding_time_limit":90,"operating_mode":"AutoManaged","ratio_limit":-1,"save_path":"/volume3/T3/PT/UploadOnly","seeding_time_limit":"2160","skip_checking":false,"stopped":false,"tags":["BTSCHOOL"],"upload_limit":-1,"use_auto_tmm":false},"addPaused":false,"assignedCategory":"Temp","savePath":"/volume3/T3/PT/UploadOnly","torrentContentLayout":null}
