### ISSUE TITLE
[Feature Request]: Place the search bar into main app bar

### ISSUE THREAD

**Issue by raylapse** [VueTorrent/VueTorrent#1578]
### Description

Currently the search bar uses one dedicated line on the UI
Is is possible to move it into the central of the main app bar so that we can gain more space for the torrent list?
I think this should be a mordern Ux design, can be widely seen in other apps.

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by raylapse** [comment]
And another enhancement on UI could be:
In RSS review, provide a button to manually refresh the RSS, rather than the user have to open Settings and refresh there.

**Comment by WDaan** [comment]
> And another enhancement on UI could be:
> 
> In RSS review, provide a button to manually refresh the RSS, rather than the user have to open Settings and refresh there.

That's a good suggestion, please open another dedicated issue for this.

**Comment by WDaan** [comment]
As for search, it was discussed here: https://github.com/VueTorrent/VueTorrent/issues/891

I personally (others might disagree) don't really see the value for another rework just to have that small amount of extra vertical screen real estate.

**Comment by Larsluph** [comment]
> I personally (others might disagree) don't really see the value for another rework just to have that small amount of extra vertical screen real estate.

Totally agree with you on that.

We can always keep it open if someone in the community is willing to do it.

**Comment by raylapse** [comment]
> > And another enhancement on UI could be:
> > In RSS review, provide a button to manually refresh the RSS, rather than the user have to open Settings and refresh there.
> 
> That's a good suggestion, please open another dedicated issue for this.
> 
> I don't use RSS at all, that's why I was hesitant to support it at first because I won't come across any these UX awkward situations. Thanks for reporting

Many thanks for all contributors! I created this in https://github.com/VueTorrent/VueTorrent/issues/1586
