### ISSUE TITLE
[Feature Request]: "No Ratio" instead of -1

### ISSUE THREAD

**Issue by Larryadd** [VueTorrent/VueTorrent#1596]
### Description

Hi,

when torrents have no ratio limit, the limit displayed is -1 or -2 depending if it's the global parameter or if it's defined individually.
I don't know if it's possible but it could be great to have some kind of text instead of the -1 or -2, like "no ratio" or "none"

also, is there a way to change the color of the categories or it's random ?

Thanks again for the amazing work and all the features updates. (love the ratio colors !)

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
Thanks for the feedback and support! 🙏

Category / tag colors are random because we can't store them globally at the moment, only in your browser instance.

To come back to your request it should be fairly easy to implement 👀

**Comment by Larryadd** [comment]
thanks for the reply,
For the tag / cat, that's what I thought.

I had a specific thing in mind.
In table mode, when I display "ratio", I have that : 

![image](https://github.com/VueTorrent/VueTorrent/assets/7392502/130804ae-3a48-4f0e-b90e-214a362bb0b7)

maybe it could be changed with some text instead of the -1 or -2. It's easier to spot the torrents with actual ratio.
