### ISSUE TITLE
[Improvement]: Improve app performance by removing the extra info call

### ISSUE THREAD

**Issue by flashlab** [VueTorrent/VueTorrent#1606]
### Bug description

![image](https://github.com/VueTorrent/VueTorrent/assets/4102853/2ed0afa4-d676-4b3b-b073-0469f2b62a86)
Please notice the requests marked with arrow, browser will keep fetching `torrents/info`. While I have a huge number of torrents, this behaviour will  occupy considerable resources of network and cpu/memory.

### Expectations

Stop calling this API periodly unless necessary，just like the default webui does.

### Steps to reproduce

1. Open a fresh vuetorrent page
2. Observe the network panel of Devtools

### How did you install VueTorrent?

Built from source

### Environment description

```plain text
Device type and name: PC
OS: Win11

PWA: No
Running inside a container: No
```

### qBittorrent version

4.6.2

### VueTorrent version

2.7.2

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by Larsluph** [comment]
We use those to handle sorting on qbit side. It will be reworked with the internal sorting system when we have time.
