### ISSUE TITLE
Selection not cleared when moving torrent to a different category

### ISSUE THREAD

**Issue by maxiwheat** [VueTorrent/VueTorrent#1623]
### Bug description

If I'm a in a list of torrents with a filter on a single category (or Uncategorized) and I select a few torrents and then with the context menu I select Set Category -> Another Category, my torrents get moved to a new category, which does not fit the filter I previously set. The torrents disappear from the view, but they remain selected, which I found misleading since I don't see them anymore. Moreover, if I keep selecting other torrents they are added to the selection.

Selection (notice the torrent count in the upper right):
![image](https://github.com/VueTorrent/VueTorrent/assets/1927334/cd483da1-2428-4bc9-a326-63155699bc16)

After moving them to a different category:
![image](https://github.com/VueTorrent/VueTorrent/assets/1927334/c6a388a7-ee53-4686-b447-f5e4c3b3bb46)

### Expectations

The selection should be cleared from the torrents that don't fit the filter anymore.

### Steps to reproduce

1. ...
2. ...
...

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type and name: 
OS: Docker in Unraid

PWA: ?
Running inside a container: Yes
```

### qBittorrent version

4.6.3

### VueTorrent version

2.7.2

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by Larsluph** [comment]
> The selection should be cleared from the torrents that don't fit the filter anymore.

Not sure if that should be the way to go. Let's say you want to change category of several torrents by searching them with their name, it will become impossible if we follow your idea.

I think filtering after an action (changing tag / category) would be better UX-wise.

**Comment by maxiwheat** [comment]
> > The selection should be cleared from the torrents that don't fit the filter anymore.
> 
> Not sure if that should be the way to go. Let's say you want to change category of several torrents by searching them with their name, it will become impossible if we follow your idea.
> 
> I think filtering after an action (changing tag / category) would be better UX-wise.

That makes sense, but you would need to re-pop de selection tool to continue selecting more torrents.

My typical use case (which lead me to create this issue): 

1. My filter is set by default to "Uncategorized"
2. That filter returns 12 torrents
3. I pop the selection tool, the checkboxes appear
4. I select 5 torrents among the 12 returned
5. I set their category to Cat1
6. Now I've got 7 torrents I can see in Uncategorized, the selection checkboxes are still displayed
7. I select 3 torrents among the 7 remaining (thinking that the 5 I moved previously aren't selected anymore since I can't see them)
8. I set their category to Cat2
9. Now my 5 first torrents + 3 torrents are in Cat2 without noticing it

Also, this leads to strange results in selection numbers (in this case I was moving the only 2 torrents in Uncategorized to a specific category):

![image](https://github.com/VueTorrent/VueTorrent/assets/1927334/a30457c7-7764-46df-87ee-058d46e5625a)

**Comment by Nocifer** [comment]
Came here from #1997.

> Not sure if that should be the way to go. Let's say you want to change category of several torrents by searching them with their name, it will become impossible if we follow your idea.

I'm not sure I completely understand this example, but even so, I do believe that no matter the possible scenario, anything that is filtered out should be considered as non-existent for the purposes of torrent selection, because performing actions on hidden torrents can easily result at best in messed up categories/tags/etc and at worst in inadvertently deleted data that is unrecoverable.
