### ISSUE TITLE
[Feature Request]: Add missing RSS rule definition settings

### ISSUE THREAD

**Issue by levlist** [VueTorrent/VueTorrent#1635]
### Description

Some options are missing from the RSS rule editor even if you want create a new rule or you want to edit the existing one.

Missing options:
- Assign Category drop-down menu
- Save to a Different Directory with 'Save to' input field
- Add Paused
- Torrent content layout.

Workaround: Switching back to the stock UI create or edit the RSS rule and switching back to VueTorrent.

### Describe the solution you'd like

Above mentioned features to be available.

### Complementary informations

- [X] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
Even using the torrent params button at the top?

**Comment by levlist** [comment]
You are right, I did not check that option. Sorry for that.
I close the ticket.
