### ISSUE TITLE
[Bug]: No add torrent window when using the magnet handler

### ISSUE THREAD

**Issue by reyqn** [VueTorrent/VueTorrent#1642]
### Bug description

Since the view3 rewrite, whenever I add a magnet from the handler, the login window flashes quickly, followed by nothing.

### Expectations

The add torrent dialog should pop so that I can add the torrent from the magnet.

### Relevant debug informations

```shell
Url looks like this: https://10.6.0.1:8090/#/download=magnet%253A%253Fxt%253Durn%253Abtih%253ARQJWBY6JHZTKCYVATQLJ.........

No errors in console or network tab
```

### Steps to reproduce

1. open a magnet link in firefox

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type and name: 
OS: Windows 11 client on firefox, raspberry pi OS (bookworm) server

PWA: No
Running inside a container: Yes
```

### qBittorrent version

4.6.4

### VueTorrent version

2.7.3

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by reyqn** [comment]
So after creating the issue, it occurred to me I could try in another browser. This does work on MS Edge, so it seems like this is an issue with Firefox. If you have any insight I'm happy to ear it.

**Comment by Larsluph** [comment]
The link is invalid. This template was the one we used before 2.0. Try registering the magnet handler again to refresh the URL.

It should be something like `http://10.6.0.1:8090/#/magnet/magnet%253A%253Fxt%253Durn%253Abtih%253ARQJWBY6JHZTKCYVATQLJ.........`

**Comment by reyqn** [comment]
For people who would have the same issue, check handlers.json in %appdata%\Mozilla\Firefox\Profiles and remove this entry:
`{"name":"10.6.0.1:8090","uriTemplate":"https://10.6.0.1:8090/#/download=%s"},`
