### ISSUE TITLE
[Feature Request]: Add the Time Active column to the table

### ISSUE THREAD

**Issue by HeLiOn--PrImE** [VueTorrent/VueTorrent#1647]
### Description

The time active column is not displayed.
In the default UI, it shows the total time the torrent has been active, and also the total time the torrent has been seeding.

![image](https://github.com/VueTorrent/VueTorrent/assets/10486881/92384f4e-bdc6-4885-9ca5-2cb6b6d61107)

This is particularly useful when using private trackers (the ones who are invite based).
As a seed requirement, the users are often required to reach a certain ratio, or keep the torrent seeding for a certain amount of time, just in case the poor activity doesn't allow them to reach the required ratio.

### Describe the solution you'd like

I think the Time Active column can replace the Date Added. It's more relevant for the user.

### Describe alternatives you've considered

If the Date Added column has to be kept, the Time Active data could be displayed somewhere in the torrent overview page.

### Complementary informations

- [X] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
Data is already available in 2 separate fields: `time_active` and `seeding_time`.

We could aggregate them in a single field instead
