### ISSUE TITLE
The value of Seed Time Limit shown in UI is incorrect

### ISSUE THREAD

**Issue by tainewoo** [VueTorrent/VueTorrent#1648]
### Bug description

For 4320 minutes, Vuetorrents will show the value as "1h 12m 0s"
For 2880 minutes, VueTorrents will show the value as "48m"
![IMG_6017](https://github.com/VueTorrent/VueTorrent/assets/13391232/82e7685a-7a10-40da-99d4-7f2314d6e7d8)
![IMG_6018](https://github.com/VueTorrent/VueTorrent/assets/13391232/017cc605-ef4c-4048-90bf-e845a10e5ff8)

### Expectations

4320 minutes should be 72 hours,
2880 minutes should be 48 hours.

### Steps to reproduce

1. Set the seed time limit for a torrent
2. Enable the Seed type me limit chip in UI
3. Check the value shown in UI

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type and name: Synology DSM
OS: Linux

PWA: No
Running inside a container: No
```

### qBittorrent version

4.6.3

### VueTorrent version

2.7.3

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by Larsluph** [comment]
Well, another qbit documentation issue, wiki shows unit is in minute, tested with 60 and it should a minute...

**Comment by tainewoo** [comment]
Hi @Larsluph , is this fix implemented to nightly build? I tried the latest nightly build just now, and it's still failed.

**Comment by Larsluph** [comment]
It is implemented. Wrong data has already been sent to your qBittorrent. You'll have to add the torrent again for changes to take effect.

**Comment by tainewoo** [comment]
Hi @Larsluph ,
get it tested again and it is ok now, thank you

**Comment by tainewoo** [comment]
Hi @Larsluph ,
don't know why it is still fail here:
![image](https://github.com/VueTorrent/VueTorrent/assets/13391232/dbb4d37b-7f09-4de8-933b-7160e80cb338)
![image](https://github.com/VueTorrent/VueTorrent/assets/13391232/268e2c7e-628f-4b1d-bd1d-f20e1d0caaf7)

**Comment by Larsluph** [comment]
Quick question to be sure about the problem, is the amount you enter taken correctly into account?

I mean by that, if you enter 2880, will it stop the torrent before the 48h mark or is it just a displayu issue?

**Comment by tainewoo** [comment]
Hi @Larsluph ,
Yes the number works correctly, 2880 minutes means 48hours later the related behavior will be triggered for that torrent.
