### ISSUE TITLE
[Bug]: Getting 401 Unauthorized

### ISSUE THREAD

**Issue by fredmorais** [VueTorrent/VueTorrent#1650]
### Bug description

Page returns 401 Unauthorized when connecting to the Web UI even though Qbittorrent is working. I have disabled both CSRF and "Host header verification".

### Expectations

Expected to display the UI for VueTorrent.

### Relevant debug informations

```shell
When launching the app, I got an error for an environment variable missing, which was QBIT_BASE. I couldn't find any information on this Github nor in the docs, so I just created it with a random value. This made the container change from returning nothing to returning an 401 Unauthorized error, which I can not either solve nor find any information on fixing this.

I also tried using the default docker-compose.yml file instead of my existing config and the problem persists.
```

### Steps to reproduce

1. Install using the regular docker-compose.yml
2. Add an environment variable to vuetorrent called QBIT_BASE with any value
3. Accessing the 8081 port will return a 401 error

### How did you install VueTorrent?

Fetched from latest-release branch

### Environment description

```plain text
Device type and name: 
OS: Ubuntu 20.04

PWA: No
Running inside a container: Yes
```

### qBittorrent version

4.6.4

### VueTorrent version

2.7.3

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by Larsluph** [comment]
This is not a bug, what you're accessing on port 8081 is the optional VueTorrent backend. It requires a qBittorrent token to authenticate and has only been designed to be used in addition to VueTorrent.

Please refer to the wiki for a proper installation guide.
