### ISSUE TITLE
[Bug]: torrent.proerties.ratio_time_limit can not be shown

### ISSUE THREAD

**Issue by tainewoo** [VueTorrent/VueTorrent#1653]
### Bug description

1. The translation is missed including English.
2. The chip is not shown in ListView after enable it for ListView.
3. The whole TableView can not be shown after enable it for TableView.

![IMG_6019](https://github.com/VueTorrent/VueTorrent/assets/13391232/cce4b957-6ebd-4ba1-9334-39e191e491b0)

### Expectations

1. There should be translations for this proerty.
2. The value of it should be shown correctly

### Steps to reproduce

1. upgrade to latest nightly build
2. enable it for both TableView and ListView

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type and name: Synology DSM
OS: Linux

PWA: No
Running inside a container: No
```

### qBittorrent version

4.6.3

### VueTorrent version

2.7.3

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by Larsluph** [comment]
The ratio_time_limit has been replaced by the seeding_time_limit property in the last update (2.7.3). Reset your settings to update the field.
