### ISSUE TITLE
[Feature Request]: Store single file torrents in a folder

### ISSUE THREAD

**Issue by bilogic** [VueTorrent/VueTorrent#1658]
### Description

1. I set my completed downloads to save in `/downloads/completed/`
2. For torrents with multiple files, they get saved to `/downloads/completed/movie-a/movie-a.mkv`, `/downloads/completed/movie-a/movie-a.jpg` etc
3. For torrents with a single file, they get saved to `/downloads/completed/movie-b.mkv`

### Describe the solution you'd like

4. Is there a way to store this single in `/downloads/completed/movie-b/movie-b.mkv`?

### Describe alternatives you've considered

n/a

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by bilogic** [comment]
Fixed it, `Torrent Content Layout`'s `Create Subfolder` did not work until I clicked `Reset Form`

**Comment by Larsluph** [comment]
You can try the "Create subfolder" content layout.

For any complaints about internal torrent management, refer to the qbittorrent/qBittorrent repo instead.
