### ISSUE TITLE
[Feature Request]: Default tag and category when adding torrents

### ISSUE THREAD

**Issue by bilogic** [VueTorrent/VueTorrent#1659]
### Description

I have to select tag and category every time I add a torrent

### Describe the solution you'd like

Can we have a default tag and category selected when we add torrents?

### Describe alternatives you've considered

n/a

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
I don't really see the added value of that... Moreover, qBittorrent doesn't allow for storing that information.

As an alternative, you can:
- Use VueTorrent's queue when adding several torrents at the same time (file and links)
- Use monitored folders to add torrent files with the same configuration (this method isn't configurable through API yet)

**Comment by bilogic** [comment]
I suggested that because VueTorrent "remembered" the `Torrent Content Layout` until I clicked `Reset Form` (https://github.com/VueTorrent/VueTorrent/issues/1658#issuecomment-2068045723)

Most of my downloads come in the form of magnet links, can they be sent through monitored folders?

**Comment by Larsluph** [comment]
I think qbittorrent can read text files with .magnet extension.

Also you can add multiple magnet links at once with one link per line in the add dialog.

The fact that the content layout is remembered is part of VueTorrent's queue system. The "reset form" button simply clears all fields and uses the defaults from qbit's preferences.
