### ISSUE TITLE
Queue is Mislabeled as Priority

### ISSUE THREAD

**Issue by enscott89** [VueTorrent/VueTorrent#1663]
### Bug description

Currently the Queue is mislabeled as Priority in both sorting and right click menu, . Priority allows you prioritize which files within a torrent will download first. The queue is specifically for setting the order in which torrents will download. 
![firefox_caJSOACRk6](https://github.com/VueTorrent/VueTorrent/assets/38144053/c722d9ed-4b3f-4f20-a218-06bcca3c7495)

### Expectations

The label should be changed to "Queue" instead of "Priority".

### Steps to reproduce

1. Open VueTorrent
2. Login

### How did you install VueTorrent?

Using a third-party docker image (hotio or others)

### Environment description

```plain text
Device type and name: 
OS: unraid 6.12.10

PWA: No?
Running inside a container: Yes
```

### qBittorrent version

2.8.0

### VueTorrent version

4.6.4

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by Larsluph** [comment]
In the qBittorrent terminology both files and torrents use "priority" so we kept them.

The term "queue" refers to qBittorrent's internal behaviour to manage these priorities, whereas the term "priority" refers to the position inside that queue.

Anyway all of that is just translation keys that we can change to clarify the distinction.
