### ISSUE TITLE
[Feature Request]: Export Settings should exclude Custom Title

### ISSUE THREAD

**Issue by SawkeeReemo** [VueTorrent/VueTorrent#1671]
### Description

I noticed when exporting/importing my Vuetorent settings between instances of qBT, it's also importing the Custom Title setting that changes what appears on the web browser tab.

### Describe the solution you'd like

I would suggest excluding this setting from the export in the future since those of us with more than one instance of qBT most likely would name our instances appropriately for visibility. (one of my favorite features in vuetorrent, by the way)

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
Excluding from the export will create code dependency to be efficient and that's not ideal.

If you still want it to be saved locally, I suggest that we prettify the exported JSON instead so that you can modify it however you want without having to use other tools to read it properly.

**Comment by SawkeeReemo** [comment]
Honestly, it’s not a huge issue. If it’s that much work to adjust, don’t even bother. Sort of diminishing return at that point for such a simple manual adjustment. 

Thanks for you feedback and great work on this webui! It’s my favorite of them. The only time I switch back to the native webui is when I’m working in bulk, which is not very often these days.
