### ISSUE TITLE
[Bug]: Fail to edit RSS rule

### ISSUE THREAD

**Issue by Juhao73692** [VueTorrent/VueTorrent#1683]
### Bug description

Unable to edit an existing RSS auto-download rule.
Now if I want to make some edits, I have to delete the rule and setup a new one.

BTW editing inside qbittorrent is ok.

### Expectations

The edit is expected to be applied as soon as the “save” button is pressed.

### Steps to reproduce

1. Open Settings.RSS.RULES
2. Edit an existing rule, for example changing the save path
3. Click “SAVE”
4. Close the popup window
5. The change isn’t applied.

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type and name: 
OS: macOS 14

PWA: not sure
Running inside a container: No
```

### qBittorrent version

2.5.0

### VueTorrent version

4.6.4

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by Larsluph** [comment]
Please include the associated qbit request from the devtools' network tab, (here `setRule`)

**Comment by Juhao73692** [comment]
I'm not sure how t use the dev tool but through network sniffing I've got that setRule request:
`ruleName=24S2+Spice+and+Wolf&
ruleDef={
"addPaused":null,
"affectedFeeds":[],
"assignedCategory":"",
"enabled":true,
"episodeFilter":"",
"ignoreDays":0,
"lastMatch":"13+Apr+2024+00:44:11++0800",
"mustContain":"Spice+and+Wolf",
"mustNotContain":"",
"name":"24S2+Spice+and+Wolf",
"savePath":my_save_path,
"smartFilter":false,
"torrentContentLayout":null,
"useRegex":false,
"previouslyMatchedEpisodes":[],
"priority":0,
"torrentParams":{
"category":"",
"download_limit":-1,
"download_path":"",
"inactive_seeding_time_limit":-2,
"operating_mode":"AutoManaged",
"ratio_limit":-2,
"save_path":my_save_path,
"seeding_time_limit":-2,
"skip_checking":false,
"tags":[],
"upload_limit":-1,
"use_auto_tmm":false
}
}`

**Comment by Larsluph** [comment]
@Juhao73692 Please see [wiki page](https://github.com/VueTorrent/VueTorrent/wiki/Support) for info on how to do it

**Comment by Juhao73692** [comment]
Oops, after a clean installation, this bug seems to have disappeared.
I'll record the request next time when the bug occurs.
Thank you anyway.
