### ISSUE TITLE
[Feature Request]: Sorting peers by DL or UL speed

### ISSUE THREAD

**Issue by martinjgrunwald** [VueTorrent/VueTorrent#1689]
### Description

This used to be possible in an older version where the peers were display as a table. I'd like to be able to sort them by UL or DL speed. Also, I actually liked the table view better. Maybe you could bring this back as an option just like the display modes in the main window 

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
Duplicate of #1385
