### ISSUE TITLE
[Bug]: torrent contents not shown

### ISSUE THREAD

**Issue by giulianozor** [VueTorrent/VueTorrent#1693]
### Bug description

Hello,
This happened twice on a 1.3T and 2.1T
 Torrents.
If I open the contents tab, I see only the root with a size of 0 bytes. No errors are shown.

### Expectations

I should be able to see the contents

### Relevant debug informations

```shell
Affected versions: at least 2.8.0 and 2.8.1.
This works on the default web interface.
```

### Steps to reproduce

1. Imported a large torrent via magnet
2. Wait for metadata download
3. Select torrent > show info > contents

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type and name: 
OS: alpine Linux 3.19, docker 25

PWA: no ?
Running inside a container: Yes

Browser: chrome on iPadOS 17.5
```

### qBittorrent version

4.6.0

### VueTorrent version

2.8.1

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by giulianozor** [comment]
![IMG_2738](https://github.com/VueTorrent/VueTorrent/assets/34373419/ce6529cd-5527-4fa9-8d04-d35ef51346cf)

**Comment by Larsluph** [comment]
Please include details of the files request

**Comment by giulianozor** [comment]
In the devtools I see a lot of these:

```
vue-CMGd_gjG.js:13 TypeError: Cannot read properties of undefined (reading 'push')
    at index-BWnwvcbv.js:10:54916
    at Array.reduce (<anonymous>)
    at index-BWnwvcbv.js:10:54816
    at In (vue-CMGd_gjG.js:13:1373)
    at Vt (vue-CMGd_gjG.js:13:1444)
    at Vr.u [as fn] (vue-CMGd_gjG.js:13:12196)
    at Vr.run (vue-CMGd_gjG.js:9:1517)
    at C (vue-CMGd_gjG.js:13:12661)
    at In (vue-CMGd_gjG.js:13:1381)
    at gf (vue-CMGd_gjG.js:13:3114)
Wp @ vue-CMGd_gjG.js:13
Tr @ vue-CMGd_gjG.js:13
In @ vue-CMGd_gjG.js:13
Vt @ vue-CMGd_gjG.js:13
u @ vue-CMGd_gjG.js:13
run @ vue-CMGd_gjG.js:9
C @ vue-CMGd_gjG.js:13
In @ vue-CMGd_gjG.js:13
gf @ vue-CMGd_gjG.js:13
Promise.then (async)
mf @ vue-CMGd_gjG.js:13
ui @ vue-CMGd_gjG.js:13
E @ vue-CMGd_gjG.js:13
nl @ vue-CMGd_gjG.js:9
Qu @ vue-CMGd_gjG.js:9
jr @ vue-CMGd_gjG.js:9
set value @ vue-CMGd_gjG.js:9
U @ index-BWnwvcbv.js:47
```

**Comment by Larsluph** [comment]
I found a torrent with that same error.
Are you able to tell me if a file and folder in your torrents have the same name?
That's what causing the issue on mine.

**Comment by giulianozor** [comment]
The structure is like

torrent/n1.bin/n1.bin
torrent/n2.bin/n2.bin

or sometimes:
torrent/n3.bin/n3.bin/00
torrent/n3.bin/n3.bin/01
