### ISSUE TITLE
[Feature Request]: Show the external IP in the bottom bar. 

### ISSUE THREAD

**Issue by Arturoe1** [VueTorrent/VueTorrent#1704]
### Description

Show the public IP in the bottom bar by pulling the data from a nslookup or similar. Right now there is not an easy way to extract that info and the qbittorent logs are unreliable as in long sessions that information is lost and shows "Unable to detect from logs"
Deluge has this functionality and i miss it in qBitorrent. 

### Describe the solution you'd like

something like pinging an external service twice an hour or so like : 
$realIP = file_get_contents("http://ipecho.net/plain");
included in the theme would be great. It doesn't need to be instant just to facilitate the visualization of the IP when  it is not available in the logs. 

### Describe alternatives you've considered

using IPleak torrents is not ideal as that information is not easily visible and you need to access an external site and their specific magnet link. 

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
This feature can't be done on VueTorrent as it's only a WebUI. We have no control over the server.

This could be made possible using the [optional backend](https://github.com/VueTorrent/vuetorrent-backend).
