### ISSUE TITLE
[Feature Request]: Using the enhanced version of qBittorrent, I hope an option can be added.

### ISSUE THREAD

**Issue by AbcdefgXW** [VueTorrent/VueTorrent#1709]
### Description

"I hope an option for the enhanced version can be added to automatically subscribe to tracker links. This option is not currently displayed in this version, and I always have to switch back to the default UI to set it up."

### Complementary informations

- [x] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
Please describe your issue in English or it will be closed.

**Comment by AbcdefgXW** [comment]
> Please describe your issue in English or it will be closed.

"Okay, got it. The issue has been revised."

**Comment by Larsluph** [comment]
Duplicate of #867

**Comment by AbcdefgXW** [comment]
> Duplicate of #867

v4.6.4.10
