### ISSUE TITLE
[Feature Request]: Hello, I can't find the option to download files

### ISSUE THREAD

**Issue by AbcdefgXW** [VueTorrent/VueTorrent#1710]
### Description

Hello, I can't find an option to download files. The default UI allows you to choose what needs to be downloaded or what doesn't need to be downloaded from the seed. I hope you can provide an option. Thank you

### Complementary informations

- [X] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
If you mean the preview whan adding a new torrent in the desktop version, it's not available for WebUIs unfortunately.

If you mean the standard way to add a torrent, there's a "plus" button in the top bar of the app.

**Comment by roju** [comment]
I think they are referring to the "content" tab under the torrent detail view. This tab is supposed to list all the files in a multi-file torrent with checkboxes next to each file, so you can select which files to download and which to skip. 

This feature is currently broken for me. I only see a blank screen with a search bar under this tab. If I disable VueTorrent and switch back to the default webui, the content tab is working again.

**Comment by Larsluph** [comment]
> This feature is currently broken for me.

Please open the DevTools by pressing F12. You should see an error inside the "Console" tab.

**Comment by roju** [comment]
`
Gp @ vue-BQgCUbk_.js:13
vue-BQgCUbk_.js:13 TypeError: m.children.toSorted is not a function
    at d (index-DF2-l4SD.js:32:54906)
    at index-DF2-l4SD.js:32:55084
    at Vr.fn (vue-BQgCUbk_.js:9:9419)
    at Vr.run (vue-BQgCUbk_.js:9:1517)
    at get value [as value] (vue-BQgCUbk_.js:9:9664)
    at Kn (vue-BQgCUbk_.js:9:10615)
    at TorrentDetail-BZZ-B8cw.js:2:6523
    at Object.r [as default] (vue-BQgCUbk_.js:13:4797)
    at default (index-DF2-l4SD.js:69:186262)
    at Pl (vue-BQgCUbk_.js:13:52737)
`

**Comment by Larsluph** [comment]
> TypeError: m.children.toSorted is not a function

Which browser are you using ?

**Comment by roju** [comment]
> Which browser are you using ?

Chrome

**Comment by Larsluph** [comment]
The toSorted function has been implemented in Chrome 110 (Released 2023-02-07). Make sure that your browser's version matches this.

**Comment by AbcdefgXW** [comment]
> > TypeError: m.children.toSorted is not a function
> 
> Which browser are you using ?

Chrome, EGDE, and ALOCK browsers are not working

**Comment by Larsluph** [comment]
µPlease include browser version, or refer to the following compatibility table: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toSorted#browser_compatibility

**Comment by roju** [comment]
Fixed after updating Chrome to latest version

**Comment by Larsluph** [comment]
@AbcdefgXW can you also confirm?

**Comment by AbcdefgXW** [comment]
> @AbcdefgXW can you also confirm?

It's already done, only the mobile Alock browser has issues. I can switch to a different browser, it's great
