### ISSUE TITLE
[Bug]: RSS feeds/rules tabs not showing up since 2.9.0 update

### ISSUE THREAD

**Issue by moracha** [VueTorrent/VueTorrent#1722]
### Bug description

I recall being able to _Open Settings_ -> _RSS_ -> _Rules_ to modify my RSS feed rules but after upgrading to 2.9.0 I can't seem to find it anymore.

How "RSS" tab looks now in 2.9.0:

![2024-06-03_21-46-16](https://github.com/VueTorrent/VueTorrent/assets/24765601/96965eed-9035-41c7-95cc-e31860dc9269)

How "RSS" looked previously after reverting back to 2.8.1:

![2024-06-03_22-23-52](https://github.com/VueTorrent/VueTorrent/assets/24765601/41b37290-be0a-4d4f-b6df-ecb1c6c07507)

### Expectations

Expecting "Rules" subtab that when clicked opens window to modify RSS rules

### Relevant debug informations

```shell
n/a
```

### Steps to reproduce

1. Open Settings
2. RSS Tab
3. "Rules" tab should be present that opens a new window to modify RSS rules

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
OS: Win11 Home 23H2
Running inside a container: No
```

### qBittorrent version

4.6.5

### VueTorrent version

2.9.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by Larsluph** [comment]
RSS views has been reworked in 2.9.0
See #1685 for more info
