### ISSUE TITLE
[Feature Request]: Show globale rate/speed speed limit in speed cards and graph

### ISSUE THREAD

**Issue by Seros** [VueTorrent/VueTorrent#1726]
### Description

Hi,
I just switched to VueTorrent and love it so far. One thing I'm missing though is to show the current global rate/speed limit somewhere as I'm used to have it shown on the classic Web UI as I have some scripts controlling the download and upload speed limit based on different metrics. Would be nice to have these limits shown on the Dashboard speed cards and graph to be sure the limits are automatically set correct

### Describe the solution you'd like

Having the limits in parantheses in the speed cards and colored horizontal lines for the limits in the speed graph

### Complementary informations

- [X] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
Looks like a great nice to have feature indead!

**Comment by Seros** [comment]
Cool. I'll see if I have some time to work on this myself as well
