### ISSUE TITLE
[Feature Request]: Remember the default "Sort by" value

### ISSUE THREAD

**Issue by maaaaz** [VueTorrent/VueTorrent#1727]
### Description

The current version does not allow to set permanently a default "Sort by" value for torrent sorting.

### Describe the solution you'd like

An option to permanently set the "Sort by" possible value (_Added on_ etc.).

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
This feature can't be done unless forking and rebuilding the app with your own default.
I would consider adding an exception to disable auto-clear of data for VueTorrent as we only store your settings and the qBittorrent authentication cookie.
