### ISSUE TITLE
[Bug]: The percentage progress value font color is too dark

### ISSUE THREAD

**Issue by maaaaz** [VueTorrent/VueTorrent#1728]
### Bug description

This is too dark, hard to see, especially when it's 100%, for instance:

![image](https://github.com/VueTorrent/VueTorrent/assets/1863158/60f01a09-0929-4fd3-b3a4-fa68eda31889)

### Expectations

A clearer font color value for progress percentage

### Relevant debug informations

```shell
cf. above
```

### Steps to reproduce

cf. above

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
cf. above
```

### qBittorrent version

4.5.4

### VueTorrent version

2.9.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by Larsluph** [comment]
Thanks for the report!

I already thought of this myself however the text being inside the progress bar makes it really difficult because when the bar is partially filled, either one of the 2 sides will be problematic (empty version is too bright and filled version is too dark).
This makes it really difficult to circumvent.

**Comment by maaaaz** [comment]
Can't you make it like the v1.7.1 ?
It was perfect to me:
![image](https://github.com/VueTorrent/VueTorrent/assets/1863158/90ab83a9-1c74-4c7d-801a-bcd598daec40)
![image](https://github.com/VueTorrent/VueTorrent/assets/1863158/c458477b-6177-4a7c-98e7-00d16d210de3)
![image](https://github.com/VueTorrent/VueTorrent/assets/1863158/c7d98330-f951-4d65-b118-89e732c479ed)

**Comment by Larsluph** [comment]
Text color is based on the surface color of the current theme, black for light theme, and white for dark theme. I guess that it can be forced using CSS but not sure if it will render properly. We can still try that.
