### ISSUE TITLE
[Feature Request]: Create torrent (qb 5.0)

### ISSUE THREAD

**Issue by FunctionDJ** [VueTorrent/VueTorrent#1733]
### Description

Earlier this year, a `torrentcreate` endpoint was added to qbittorrent to allow torrent creation via API, not just desktop:
https://github.com/qbittorrent/qBittorrent/pull/20366

Judging by the `Changelog` file, this will ship with qbittorrent 5.0.

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
As mentioned in #1732 this hasn't been released yet. We're waiting for the release to implement and test it on a stable build.

**Comment by terrytw** [comment]
Gently bumping this since 5.0 is rolled out and initial support has been implemented.

**Comment by Larsluph** [comment]
Something is being prepared ATM. Just need to test everything and make sure no bugs are to be found.
