### ISSUE TITLE
[Feature Request]: The tracker tab is messy

### ISSUE THREAD

**Issue by maaaaz** [VueTorrent/VueTorrent#1735]
### Description

The tracker tab is messy right now, especially when there's a [huge list of trackers added](https://github.com/ngosang/trackerslist), we have to scroll a lot:

![image](https://github.com/VueTorrent/VueTorrent/assets/1863158/787ef6cd-6416-4958-98c0-4984c4aedee8)

It used to be really clear and synthetic in previous versions (such as the 1.7.1) without the need of scrolling:
![image](https://github.com/VueTorrent/VueTorrent/assets/1863158/783d4a8c-4ed6-4034-a3f0-e61775e7ea0f)

### Describe the solution you'd like

More like the 1.7.1, a simple, clear and quick overview of trackers, without the need of scrolling.

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
This was made at the time Vuetify 3 data table weren't ported yet. It is now available as of Vuetify v3.6.0 (Nebula).
