### ISSUE TITLE
[Bug]: VueTorrent Breaks with Linuxserver.io release 4.6.5-r0-ls335 of qBittorrent

### ISSUE THREAD

**Issue by daNutzzzzz** [VueTorrent/VueTorrent#1736]
### Bug description

With the latest release of qBittorrent from Liniuxservier.io, you get the following error (`Unacceptable file type, only regular file is allowed`.) when using custom webUI like VueTorrent. 

Changing `WebUI\AlternativeUIEnabled` from `true` to `false` allows the default WebUI to load, or reverting back to release [4.6.5-r0-ls334](https://github.com/linuxserver/docker-qbittorrent/releases/tag/4.6.5-r0-ls334) allows you to use VueTorrent

### Expectations

VueTorrent Custom WebUII loads and isnt presenting an error.

### Relevant debug informations

![](https://github.com/VueTorrent/VueTorrent/assets/89404081/d3f70650-7004-4195-8847-8476b2698471)

### Steps to reproduce

1. Use container release [4.6.5-r0-ls335](https://github.com/linuxserver/docker-qbittorrent/releases/tag/4.6.5-r0-ls335)

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type and name: 
OS: Ubuntu 22.04.4 LTS / Docker 26.1.3

PWA: Yes / No
Running inside a container: Yes
```

### qBittorrent version

4.6.5

### VueTorrent version

2.9.0

### Agreements

- [ ] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [x] A similar issue doesn't already exist

**Comment by Larsluph** [comment]
Please ensure that your VueTorrent folder is accessible inside your qBittorrent container and correctly mapped in the qBittorrent preferences.

**Comment by rahul-sha** [comment]
I have the same issue after the recent qbittorrent update.
Then I recalled using this mod, where we added an environment variable called DOCKER_MODS in the docker compose:
` - DOCKER_MODS=arafatamim/linuxserver-io-mod-vuetorrent`
I suspect this is the cause.

**Comment by one-eeyed** [comment]
> Please ensure that your VueTorrent folder is accessible inside your qBittorrent container and correctly mapped in the qBittorrent preferences.

i use the docker_mods method to use the ui, after the update there isn't any /vuetorrent path, but a arafatamim.linuxserver-io-mod-vuetorrent.latest file instead.

**Comment by Larsluph** [comment]
In that case please contact the repo in question. We aren't responsible for his actions.
