### ISSUE TITLE
[Feature Request]: file count, truncated hash, and basename(save_path) chips

### ISSUE THREAD

**Issue by ShanaryS** [VueTorrent/VueTorrent#1737]
### Description

I would like a couple extra chips to add to the customization
1. Number of files within a torrent
2. Hash but only the first 8 characters
3. Only the last folder of save_path, basename(save_path)

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
1. File count can only be obtained per torrent so it can't be added.
2. We could made hashes always truncated in the dashboard? If needed you can still copy hash in the right click menu or get it in the torrent info page.
3. I like the idea, again should it be always truncated in the dashboard to reduce maintenance cost?

**Comment by ShanaryS** [comment]
I'm sorry, I wasn't clear. All of these features I only want on the home page (dashboard?). The list, table, and grid views. Basically as another checkbox for what to display on incomplete/complete torrents.

I agree with the always truncating for display. I don't think you can even copy from the dashboard. Doing it for save_path might lose info in some people's setup but I find it unlikely.

> File count can only be obtained per torrent so it can't be added.

I'm not sure I understand, per torrent is how I'm envisioning it.

**Comment by Larsluph** [comment]
> I'm sorry, I wasn't clear. All of these features I only want on the home page (dashboard?). The list, table, and grid views.

That's what I understood.

> I don't think you can even copy from the dashboard.

You can only copy the name, hash and magnet link of a torrent from the right click menu.

> > File count can only be obtained per torrent so it can't be added.
> 
> I'm not sure I understand, per torrent is how I'm envisioning it.

What I mean by that is that we can't fetch that data in bulk like everything else. One request = one torrent, so to get that data we must do n request for n torrents. It's unthinkable.

> While we're at it, I think making content path relative to save_path would also make sense, but I personally do not use it.

I think it will add a lot of load for nothing. Content path is the location where torrent data is currently stored (with parent subfolder if there is one), `download_path` for unfinished torrents and `save_path` for finished ones, and it may not be true in rare cases.

**Comment by Larsluph** [comment]
> Is there there any way to cache the count it so it only has to be done once per torrent?

It must be possible but depending on the torrent count of the user it may cause slowdowns at the startup. Try looking at the qBittorrent repo to submit an issue there to add that file count property to the torrent payload.

Now idk what's the best way to do the other two :
- "permanent" truncature in the dashboard ?
- Configurable parameter ?
- Separate properties ?

@WDaan What do you think?

**Comment by WDaan** [comment]
I think that endless configurability, becomes a pain at a certain point 😅

For the folder basename, it can probably be a new 'item' and should be okay. Wouldn't turn this into a setting.
