### ISSUE TITLE
[Feature Request]: Export .torrent should export as torrent name, not hash number (Bonus: multiple in folder/zip file)

### ISSUE THREAD

**Issue by SawkeeReemo** [VueTorrent/VueTorrent#1741]
### Description

When you export a torrent from the standard qBT webui, it exports as the actual torrent name. But when you export a torrent with vuetorrent as the webui, it exports as the hash number, and therefore you have no idea what the .torrent file is for until you reimport it.

NOTE: I'm running qBT v4.6.4

Secondly, I would love it if you could make it so that if I export multiple .torrent files, instead of having to "ok" through each one individually, it would be great if they could be exported as a single package like a zip file or folder.

### Describe the solution you'd like

1. Export as torrent name, not hash number
2. Export multiple in folder or zip file

### Describe alternatives you've considered

I have to switch to the standard webui to export .torrent files if I want to know what they are.

### Complementary informations

- [X] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
Torrent hash were used to prevent duplicates from being overwritten. One should add a check and maybe a warning to alert the user that some duplicates are present.

ZIP export should be fairly simple to do.

**Comment by SawkeeReemo** [comment]
That's a good point. What about maybe adding the hash to the end of the torrent name or something to avoid dupes? Might be a long file name, but you'd get the best of both worlds that way. Maybe?

**Comment by Larsluph** [comment]
> Might be a long file name, but you'd get the best of both worlds that way.

By default, Windows does have a path length limit so it might impact a lot of users actually. I know current versions can handle them but idk at what point.

Maybe if we truncate the title and hash to a certain limit? e.g. we take the first 30 characters from the title and 8 from the hash.

**Comment by SawkeeReemo** [comment]
sorry for the lag in my reply, been a rough couple weeks over here. I was thinking the best case would be just keep the torrent name, and either truncate the hash at the end, or if you can do similar to what macOS does where they add a (1) to the end of the file name. ...albeit, please don't use (#) haha, just an underscore and a number would suffice, I think. I'm not sure how useful having the hash in the torrent file name is for anyone (maybe?), other than to prevent dupe overwrites on export.

**Comment by Larsluph** [comment]
That could be a workaround, now that I think of it browsers may already do that by default. It may be great to check that beforehand.
