### ISSUE TITLE
[Feature Request]: Display item counts for states/categories without filtering for them

### ISSUE THREAD

**Issue by dangitall** [VueTorrent/VueTorrent#1744]
### Description

There is no quick way to see how many torrents are in a certain state or category. For example, the only way to see if any torrents are in the error state is to enable that filter. I'd prefer to only have to enable the filter if I know there are torrents that need attention.

### Describe the solution you'd like

Maybe a new configurable section could be added to the sidebar where users can choose certain filter combinations that will always display the count of torrents that satisfy that filter.

### Complementary informations

- [X] Is this feature already implemented in the default WebUI?

**Comment by WDaan** [comment]
I like that! That's a pretty neat idea

**Comment by jagadam97** [comment]
[branch with only adding count of torrents to active, error, offline torrents states](https://github.com/jagadam97/VueTorrent/commit/cef6cbc1f1c879df87988277c7ea7e7395aafe50)

I would argue that this will be enough data for someone to glance if they are only looking for states of torrents for quick filtering.

But would be happy to implement this across all the filters adjacent to the filter value.

if we would like to implement it for all the filters and filter values i would like to know if we want to be 

1. just no. of torrents with that particular filter (Computationally Litght) (Current Default WebUI implementation)
                             or
2. only torrent of that particular filter with all the selected filters satisfied (Computationally heavy)

**Comment by dangitall** [comment]
Awesome! I would find it useful to have it implemented for all filters (e.g. I would use it to see if I have any Uncategorized torrents). AFAIC, the lightweight option is fine, but I'm not sure what makes the most sense from a UX perspective.
