### ISSUE TITLE
[Feature Request]: Search torrents based on torrent contents

### ISSUE THREAD

**Issue by admlko** [VueTorrent/VueTorrent#1767]
### Description

I have lots of torrents which are collections of a lot of different files.
It would be handy to be able to search torrents based on torrent contents file names.

### Describe the solution you'd like

For example, if I enter .txt in the search field, it would show all torrents which content files include .txt files.

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
Unfortunately, torrent content can only be retrieve one-by-one. It's the same problem as in #1737
