### ISSUE TITLE
[Bug]: Ordering by Name broken

### ISSUE THREAD

**Issue by Phil57** [VueTorrent/VueTorrent#1768]
### Bug description

With version 2.10.2, ordering torrents by Name seems to be broken

### Expectations

Order list by name when this option is selected

### Relevant debug informations

```shell
Version 2.10.2
QB 4.6.5
```

### Steps to reproduce

Order list by Name

### How did you install VueTorrent?

Fetched from latest-release branch

### Environment description

```plain text
Ubuntu
Running inside a container: Yes
```

### qBittorrent version

4.6.5

### VueTorrent version

2.10.1

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by Larsluph** [comment]
Could you provide an example? Only the first few letters should be enough to understand the issue here.

**Comment by Phil57** [comment]
![Screenshot from 2024-06-29 19-07-45](https://github.com/VueTorrent/VueTorrent/assets/10242493/8dd85008-2165-4511-9f1c-7dcf20320a9c)

**Comment by Larsluph** [comment]
Thanks for the report, it was indeed a mistake while applying comparators to the name field.
All others should work as expected

**Comment by Phil57** [comment]
Yes, other work. Thank you.
