### ISSUE TITLE
[Feature Request]: More Sorting Options

### ISSUE THREAD

**Issue by hl2guide** [VueTorrent/VueTorrent#1780]
### Description

Some useful sorting is missing from the main download list.

### Describe the solution you'd like

Unless already possible please add the ability to sort the main list by:

- Title
- Size
- Progress
- ETA

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
Either I don't understand or we aren't talking about the same thing but those are already available in the torrent list.

You can change the sorting method by clicking on the select field at the top of the list. The properties you mentioned are in the list as the exact names you provided.

**Comment by hl2guide** [comment]
ahh  I found that mouse scroll ability.
