### ISSUE TITLE
[Perf] UI freezed while seeding 5000+ torrents

### ISSUE THREAD

**Issue by flashlab** [VueTorrent/VueTorrent#1786]
As first descirbed in #1762 , if more than 5000 torrents are under seeding state, the web UI will freeze right after torrent list show up. And all mouse/clipboard interactions are non-responsible.
If all seeds are paused, the issue will gone.
After applying the latest patch #1784 , the issue still exists.

I suppose if the regular UI  updating job(such as sorting) can be disabled if seeding counts exceed a certain number(let's say 1000), and only updating if filter state changes which triggered manually ;)

**Comment by Larsluph** [comment]
@flashlab 
For better understanding of the issue, i can ask you to capture some debug data.

Here's a build with some debug symbols included: [vuetorrent.zip](https://github.com/user-attachments/files/16289856/vuetorrent.zip)

Here's how you can proceed to record everything needed:

1. Go to a VueTorrent instance where you notice freeze.
2. Head to the Performance tab of the DevTools.
![image](https://github.com/user-attachments/assets/835a80a2-7996-45e8-b538-100d6c1aa40f)
3. Untick the screenshot box at the top to prevent leaking your data, we don't need them.
4. Click on the record button to start recording browser's performance stats.
5. Wander around in the interface where it's freezing, less than a minute should be more than enough.
6. Click again on the record button to stop the recording
7. Click on the download arrow next to it to save the profile, it should ask you to save a JSON file. This will contain every captured data.

You can either reply here with the JSON or [send me an email](mailto:vuetorrent@larsluph.dev).

**Comment by flashlab** [comment]
@Larsluph Sorry for the late reply. I test the file you offerd
> Here's a build with some debug symbols included: [vuetorrent.zip](https://github.com/user-attachments/files/16312608/vuetorrent.zip)

And the UI is very smooth without any frame drop!
But the problem still exists from the latest [build](https://github.com/VueTorrent/VueTorrent/actions/runs/10008820456) 
I send the performance log file through email. Thanks for your patient ;)

**Comment by Larsluph** [comment]
> And the UI is very smooth without any frame drop!

Awesome! The build I gave you already included some basic performance fixes but I had the same results with mocks so the mock does introduce some performance issues.

> But the problem still exists from the latest [build](https://github.com/VueTorrent/VueTorrent/actions/runs/10008820456)

So it confirms the fixes I included inside the build 😄 Perfect 🙌 

> ~I send the performance log file through email.~ The email address is not reachable, if you could provide another one I'll try to send again.

Depending on the time you sent the email it may be due to the Microsoft outage, I tried and the email works now so please try again.
