### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by woeisme** [VueTorrent/VueTorrent#1787]
### Description

I'd really appreciate a Flatpak roll of this added to Flathub for those of us that prefer to run software that way. Your tool looks great to use as a frontend for docker-qbittorrent-nox and many of us are searching for a decent WebUI frontend but the lack of Flatpak is a deal-killer for many of us. 

### Describe the solution you'd like

create a flatpak installer for VueTorrent

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
From what I understand, flatpack is a package utility manager. In that case, I'm not sure that VueTorrent is appropriate for that kind of use case as it is only a WebUI and not a standalone software 🤔
