### ISSUE TITLE
[Feature Request]: Display torrent private state

### ISSUE THREAD

**Issue by Phil57** [VueTorrent/VueTorrent#1820]
### Description

In the torrent details, we have the private state of a torrent.
Add the possibility to display that information in the List / Grid / Table views.

### Describe the solution you'd like

New column / "entry" in the different views with the private state of a torrent.
A checkbox is good enough, no need to have full text (to minimise column width in table view)

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
This kind of information is only available using the `/properties` endpoint of qBittorrent. Unfortunately, this data can only be called for a single torrent at a time.

Depending on the number of torrents registered this can drastically increase initial load time and thus can't be implemented for a fluent user experience.
