### ISSUE TITLE
[Bug]: Table column header sorting, not working with torrent title

### ISSUE THREAD

**Issue by Phil57** [VueTorrent/VueTorrent#1827]
### Bug description

With the new table sort view from [1819](https://github.com/VueTorrent/VueTorrent/issues/1819) (**thank you !**), everything works perfectly except that we cannot sort by torrent title

### Expectations

Add torrent title sort option

### Relevant debug informations

```shell
VueTorrent Nightly 831ac9b
qBittorrent 4.6.5
```

### Steps to reproduce

1. Swith to table mode
2. Try to sort torrent by title from column header

### How did you install VueTorrent?

Fetched from nightly-release branch

### Environment description

```plain text
Running inside a container: Yes
```

### qBittorrent version

4.6.5

### VueTorrent version

2.22.1 Nightly 831ac9b

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by Larsluph** [comment]
Forgot that column indeed, thanks for the quick feedback!

**Comment by Phil57** [comment]
Thanks to you for the quick implementation and fix !
