### ISSUE TITLE
[Bug]: In lower version browsers, errors occur "e.value.union is not a function"

### ISSUE THREAD

**Issue by myml** [VueTorrent/VueTorrent#1838]
### Bug description

The Set.union method has only recently gained browser support, so it may cause errors in older browsers, leading to UI malfunctions. For example, main page does not refresh automatically.

Chrome and Firefox will only support [Set.union](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/union#browser_compatibility) in 2024. Is it too aggressive to use it now? There are other ways to merge sets, such as using new Set(Array.from(set1).concat(Array.from(set2)));.

code: https://github.com/VueTorrent/VueTorrent/blob/7519449a12ad6365d0e06d57d3e141a2f3e9d76f/src/stores/tags.ts#L18

### Expectations

The UI is not functioning properly.

### Relevant debug informations

```shell
TypeError: e.value.union is not a function
    n https://dl.keywaishe.com/assets/index-D8T0Ybyg.js:71
    D https://dl.keywaishe.com/assets/vue-CbXlR1F-.js:25
    M https://dl.keywaishe.com/assets/index-D8T0Ybyg.js:71
```

### Steps to reproduce

1. install firefox 122
2. open VueTorrent UI
3. F12 open console

### How did you install VueTorrent?

Using a third-party docker image (hotio or others)

### Environment description

```plain text
Device type and name: 
OS: debian

PWA: No
Running inside a container: Yes
```

### qBittorrent version

2.11.1

### VueTorrent version

4.6.5

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by Larsluph** [comment]
> Chrome and Firefox will only support [Set.union](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/union#browser_compatibility) in 2024. Is it too aggressive to use it now?

I hear that and I see the problem of using latest features as soon as they are released. However I feel like browsers are software that handles sensitive piece of a computer and that they should be updated as soon as possible. Moreover, I helps keeps the code clean and concise.

> There are other ways to merge sets, such as using new ` Set(Array.from(set1).concat(Array.from(set2)));`.

In that case it would be easier and cleaner to just use arrays instead of sets to be honest.

Given the fact that it is a "critical" part of the app, we can revert using sets to ensure a better compatibility with everyone.
