### ISSUE TITLE
[Feature Request]: Add a panel with torrent informations

### ISSUE THREAD

**Issue by pokemaster974** [VueTorrent/VueTorrent#1840]
### Description

Hi, I've searched into the VueTorrent's settings but haven't found such setting.
Is it possible to add an option that when we click on a torrent it will display directly an informations panel (like in the default panel) ?
The panel could be se same as with right click -> Show info or a more condensed panel.

An alternative could be that a double click will display this panel (actually it seems that double click made a select/unselect).
Regards.

### Complementary informations

- [X] Is this feature already implemented in the default WebUI?

**Comment by pokemaster974** [comment]
Ok, I understand that I need to uncheck "select mode" to have the double click working.
I just let it open to have your feedback about a below permanent panel showing the torrent informations. And feel free to close it if necessary.

**Comment by Larsluph** [comment]
Do you mean something like in #1638? If not, I'm not sure to understand your request.

**Comment by pokemaster974** [comment]
> Do you mean something like in #1638? If not, I'm not sure to understand your request.

I mean something like the original UI :
![image](https://github.com/user-attachments/assets/f38fbde1-6637-4e61-8017-6a13c950a941)

I'm thinking of something like that :
![image](https://github.com/user-attachments/assets/f35cb09d-1ea9-4629-ad0c-a19a002c1f4a)
And when we select a torrent, it refreshes and displays the informations about the selected torrent.

**Comment by pokemaster974** [comment]
The issue I see with the current behaviour is that informations panel is displayed on all the webUI and we need an extra click (after the double click or the right-click -> show info) to close it. Having a bottom panel removes this extra step to close it.

**Comment by Larsluph** [comment]
Oh ok now I understand. I like the idea of removing that click barrier but I don't know if it's really something we should do.

For the table view on desktop it does looks great, but for all the other configurations, whether on mobile or with the list and grid view it doesn't look great as it takes a lot of space.
