### ISSUE TITLE
[Feature Request]: Improve keyboard interaction on Sort By pulldown

### ISSUE THREAD

**Issue by dangitall** [VueTorrent/VueTorrent#1841]
### Description

Right now (on v2.11.1) if you click on the text of the Sort By menu it works like a text edit box, dropping the cursor wherever you clicked and letting you edit the whole field. This is better than not having keyboard input at all, but since changing the text to something arbitrary isn't useful I think it would be better to have the dropdown just respond to keypresses by searching for the letters typed.

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
This would indeed improve the ease of use, and prevent errors when entering invalid values.

However the v-select component is kind of weird for that. It does allow to pre-select values using your keyboard but only when you focus the component. As soon as you use the arrows to select a value, search typing doesn't work anymore unless you unfocus and focus it again.

Even with this limitation I think it remains better.
