### ISSUE TITLE
[Bug]: 2.11.0以后的版本会出现添加完磁力页面不刷新问题

### ISSUE THREAD

**Issue by edu6666** [VueTorrent/VueTorrent#1849]
### Bug description

2.11.0以后的版本（2.11.1及2.11.2）会出现添加完磁力链接页面不刷新显示问题，需要手动刷新页面才会
![1122](https://github.com/user-attachments/assets/c3c4ef2b-9a3e-49b0-a51c-501572d69513)
![_20240812192133](https://github.com/user-attachments/assets/08cb626b-bf53-439b-af12-1919ba9e403c)
需要刷新以后才显示
![_20240812192247](https://github.com/user-attachments/assets/a3184325-592b-4ed3-9133-17cbdbb5ec65)

### Expectations

尊敬的作者，希望您能够改善这个问题

### Relevant debug informations

```shell
无
```

### Steps to reproduce

1. ...
2. ...
...

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type and name: 
OS: Chromium 118.0.5993.159

PWA: Yes / No
Running inside a container: No
```

### qBittorrent version

4.6.5.10

### VueTorrent version

2.11.1和2.11.2

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist

**Comment by Larsluph** [comment]
Please redact issues in English.

For any errors, please include console errors in the debug informations.
