### ISSUE TITLE
[Bug]: ETA shows infinite symbol when it showing >10 days

### ISSUE THREAD

**Issue by daviddanko** [VueTorrent/VueTorrent#1851]
### Bug description

I have a rule which deletes torrents older than 30 days. The time remaining is shown in the ETA column. On the version 2.10.2 the time is correct always. On the newest version 2.11.2 when the ETA is more than 10 days, it shows the infinite symbol ∞.

### Expectations

Should show the correct time even if it is more than 10 days.

### Relevant debug informations

.

### Steps to reproduce

1. Download the newest vuetorrent. 
2. In the GUI go to settings - bittorrent - speed limits and set the option 'when seeding time reaches 43200 (minutes) [30 days].
3. Download something and check the ETA column. There will be an infinite symbol.
4. Set the value in step 2 to 12960 minutes (9 days) and check the ETA column. Correct time value should be shown.

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
OS: Debian
Running inside a container: Yes
```

### qBittorrent version

5.6.5

### VueTorrent version

2.11.2

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by Larsluph** [comment]
Good catch! I just forgot a 0 in the max value threshold 😅
