### ISSUE TITLE
[Feature Request]: Auto discover vuetorrent backend

### ISSUE THREAD

**Issue by highfredo** [VueTorrent/VueTorrent#1866]
### Description

Instead of not configuring any backend by default, vuetorrent could try to discover its backend automatically.

For example, if qbittorrent/vuetorrent is hosted at https://torrent.example.com, it could try to discover the backend at https://torrent.example.com/vuetorrent-api/

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
With 2.0 update of the backend, this can now be implemented.
