### ISSUE TITLE
[Feature Request]: Add dialog box for renaming folder when Create Folder is selected

### ISSUE THREAD

**Issue by Marquis-deCarabas** [VueTorrent/VueTorrent#1871]
### Description

In the native GUI of qBittorrent (not the native Web UI), it is possible to modify the new parent folder created when "Create Folder" is selected. This isn't possible in any Web UI's I've seen, both native and custom.

### Describe the solution you'd like

When Create Folder is selected, a dialog box should appear (or be enabled or however it makes sense to the devs) that allows the new folder to be custom named, instead of taking the name of the torrent.

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
This in fact can't be done so easily inside a WebUI as the torrent preview data is only available inside the GUI app. No API routes are exposed to fetch this data.

Moreover, we have no way of knowing whether the torrent used that extra folder so it would require extra attention if we really want to implement this.

A workaround can be made by trying to rename the top-most folder as soon as the torrent is added.
This can work for torrent files if we assume that the newly created folder's name is the name of the torrent but not for magnet links, or at least not all of them.

Anyway you can still do it manually by renaming files to include that extra folder.
