### ISSUE TITLE
[Bug]: A Peer IP without a Country Flag Messes up Peers View

### ISSUE THREAD

**Issue by TheCoolestPaul** [VueTorrent/VueTorrent#1872]
### Bug description

Inside the Peers tab of a torrent's information, an IP that can't be resolved with a country is displayed incorrectly in the table of peers. Please see the image below.

![bug-report](https://github.com/user-attachments/assets/9abacc2e-0178-4cda-b258-2d58cde0f989)

### Expectations

I expected to see either an N/A or a blank value for the peer and all of the other information to be displayed in the correct rows, like the rows below.

### Relevant debug informations

TypeError: undefined has no properties ["item.country"]

The above error was displayed in every update frame.

### Steps to reproduce

1. Manually add a peer with a local IP (192.xxx:xxxx) to a torrent.
2. Continue to view the peer tab of torrent info while it gets the peer's country flag.
3. All values in the row are offset by one from the respective columns, see the above image.

### How did you install VueTorrent?

Using a third-party docker image (hotio or others)

### Environment description

```plain text
Device type: Desktop
OS: Windows
Browser (name and version): Firefox 129.0.2 (64-bit)

PWA: Yes
Running inside a container: Yes
```

### qBittorrent version

4.6.6

### VueTorrent version

2.12.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by Larsluph** [comment]
Thanks for the report!

Can you also include the file location of the error, and the qbittorrent response's row entry without the country data?

See [Support](https://github.com/VueTorrent/VueTorrent/wiki/Support) for help
