### ISSUE TITLE
[Feature Request]: Turn the current speed indicators in the sidebar into shortcuts for activating the downloading and uploading torrent state filters

### ISSUE THREAD

**Issue by romartobashey** [VueTorrent/VueTorrent#1879]
### Description

Whenever I open the sidebar and notice higher-than-usual speed values, I feel compelled to click on them, as they already resemble buttons, to quickly see which torrents are generating that activity. Although I have the state filter in the top bar, it's often combined with other tag, category, or tracker filters, making it not instantly accessible.

### Describe the solution you'd like

What I imagine is tapping or clicking on the upload speed value would temporarily activate the 'uploading' torrent state filter and remove any other enabled filters. Clicking again would remove the 'uploading' filter and restore the previously active filter state. There could be some visual indication when these shortcuts are active, such as a different border or background color.

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
As mentioned recently in another issue, introducing this kind of temporary store seems like a lot of complexity added.

Now that I think of it, we might be able to save a "favorite filter" state to restore it anytime you want.

Don't hesitate to create a new issue to address these changes.
