### ISSUE TITLE
[Feature Request]: Please stop the “not secure” restriction!

### ISSUE THREAD

**Issue by chuwza** [VueTorrent/VueTorrent#1896]
### Description

In the original Web UI, we can copy the magnet link, But in VueTorrent, you can't copy the link unless it's “https”, and register VueTorrent as a magnet link program.

https://github.com/VueTorrent/VueTorrent/issues/1764
https://github.com/VueTorrent/VueTorrent/issues/1414

You guys mentioned that it's a browser limitation, but I think that's an excuse because other Web UI can copy the magnet link normally, it's purely a VueTorrent limitation! 😂😥

(Such as picture, this is a alternate WebUI which called DarkLight-qBittorent-WebUI, We can copy the magnet link normally)
(https://github.com/crash0verride11/DarkLight-qBittorent-WebUI)
![image](https://github.com/user-attachments/assets/176a8318-7314-473c-aa6a-fba5ce4b51a1)

Please remove this useless restriction, we use qBittorrent on our LAN and this restriction is ridiculous!

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
According to latest recommendations, this method of copying data is **obsolete**, which means that some browsers have already dropped support for this feature and isn't recommended to use from now on.

This isn't a VueTorrent limitation and we could switch to the older method but it will not be implemented to ensure compliance with the latest browsers' recommendations.

Please note that you can generate a self-signed certificate really easily to enable https and thus enjoy all security features.

Feel free to fork or use another WebUI if you expressly need to use ancient technology.

Source: https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand
