### ISSUE TITLE
[Bug]: Having the same behaviour as qbitorrent / Add an option to keep or not the last "deleting files" setting

### ISSUE THREAD

**Issue by pokemaster974** [VueTorrent/VueTorrent#1907]
### Bug description

If "Delete files with torrent" is checked, it will remain checked the next times we will click on the trash/bin.

On qBittorrent, if we check the same option, it will be unchecked the next time we will try to delete torrents.
I think that's the official behaviour is more secure as sometimes we can click very quickly.

### Expectations

![image](https://github.com/user-attachments/assets/4895a44a-ca31-4465-af06-15e23d44f000)
and not
![image](https://github.com/user-attachments/assets/903b68b9-7858-4af3-a124-92cb5357f405)

Or at least having an option in settings to keep or not the last "deleting files" option/setting

### Relevant debug informations

None

### Steps to reproduce

1. Click to delete a torrent
2. Check "Delete files with torrent"
3. Click on Delete
4. Click to delete another torrent
...

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type: Desktop
OS: Windows
Browser (name and version): Firefox 130.0.1

PWA: No
Running inside a container: Yes
```

### qBittorrent version

4.6.0

### VueTorrent version

2.11.1

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by pokemaster974** [comment]
I saw this https://github.com/VueTorrent/VueTorrent/issues/291 but I don't find the option

**Comment by pokemaster974** [comment]
Ok, it seems intentional https://github.com/VueTorrent/VueTorrent/issues/1020
But maybe an option to keep or not the last "delete" setting could be a good idea.

Please at least think about it before tou close it. Regards.

**Comment by Larsluph** [comment]
The current behavior is to remember the state of the checkbox, whether you accept or cancel the dialog.

What you are saying is that you would like something more like qBittorrent's native bahavior, which is to make it remember on the click of a button instead of always?

**Comment by pokemaster974** [comment]
> The current behavior is to remember the state of the checkbox, whether you accept or cancel the dialog.
> 
> What you are saying is that you would like something more like qBittorrent's native bahavior, which is to make it remember on the click of a button instead of always?

Hi, ok I will try to make screenshots, maybe it will be easier.
If I delete torrent + file in qBit and choose to not keep the setting (yellow lock) :
![image](https://github.com/user-attachments/assets/211420f9-7283-42d6-953d-cc29f122c72d)
This is what I get the next time I want to delete a file :
![image](https://github.com/user-attachments/assets/1e6f3796-85b1-4c0c-a9ac-8186e310a380)

If I delete torrent + file in qBit and choose to not keep the setting (grey lock) :
![image](https://github.com/user-attachments/assets/29cd77fc-03f2-484c-ab16-fdb18101fb73)
This is what I get the next time :
![image](https://github.com/user-attachments/assets/7aa9e208-0621-4cae-91b8-8a63021deed0)

**Comment by pokemaster974** [comment]
If I choose to only delete the torrent and not files with not keeping the setting :
![image](https://github.com/user-attachments/assets/2c3a77e1-c0fa-484a-a8d9-1ffa506f3eab)
This is for the next delete :
![image](https://github.com/user-attachments/assets/4c51a9f6-f198-4b51-b9f9-c941aa9a5331)

If I delete it with the gray lock :
![image](https://github.com/user-attachments/assets/fe0d0cdf-8ded-4e51-bcb3-b052117e74e0)
I got this for the next delete :
![image](https://github.com/user-attachments/assets/e05712fa-0614-49f6-8ebc-e5a327c0ddac)

TBH, the lock is not very intuitive (I'm not very aware of this because in my case I only remark that I need to check the case only if I want to delete the file, so it's probably on the yellow lock when I delete).
But the potentiel option if VueTorrent to keep or not the "delete" setting could be acting like this :
- if the option is checked so it remember the state of the checkbox
- if the option is unchecked (to not keep the setting) it remember/save the opposite of the checkbox.

I don't know if I'm clear, if not sorry about this :/

**Comment by Larsluph** [comment]
So you want the memory of that state to be manual instead of automatic?
You choose which state you want to keep for later use?

**Comment by pokemaster974** [comment]
> So you want the memory of that state to be manual instead of automatic? You choose which state you want to keep for later use?

Yeah, if possible an option to keep the actual VT behaviour (remembering the state of checkbox) of not (always unchecked, and checked manually if we want).

**Comment by Larsluph** [comment]
With qbit 5.0, we now have a server-side field to save this state. I'll take a look about using this state if you're using qbit 5+.

qbittorrent/qBittorrent#20150

**Comment by pokemaster974** [comment]
I don't know if I have qbit 5, need to check of change container but thanks for the commit 🎆 !

**Comment by Larsluph** [comment]
I made it so that the state persist in the localStorage too so it should work anyway
