### ISSUE TITLE
Backend Question 

### ISSUE THREAD

**Issue by papampi** [VueTorrent/VueTorrent#1910]
### Bug description

I have a local installation of QB+VT and not using reverse proxy, do I still need the backend?

If not  why it shows a warning that " Backend is unreachable"  whenever I click save in settings?

Anyway to disable backend check and the warning when not using it ?

### Expectations

Dont show warning when not using backend

### Relevant debug informations

![image](https://github.com/user-attachments/assets/928af3fe-c9b8-4766-93cd-bbe9aceb72de)

### Steps to reproduce

Click save in settings when there is no backend

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type: Desktop
OS: Linux
Browser (name and version): Chrome

PWA: Yes / No
Running inside a container: Yes / No
```

### qBittorrent version

4.6.7

### VueTorrent version

2.13.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by Larsluph** [comment]
I was missing a condition ith the auto detection feature. It will be fixed in the next release.
