### ISSUE TITLE
[Bug]: Page Not Found (on login and login failed)

### ISSUE THREAD

**Issue by vdbhb59** [VueTorrent/VueTorrent#1914]
### Bug description

Not exactly sure how to describe this BUG, or if it even a BUG. I am using Debian 12 Bookworm, and installed qbt-nox first with a qbt user added to its own group as well. But the error is not due to a user.
The URL is at: https://domain/public/#/login?redirect=/ & https://domain/public/#/login (the redirect one loads automatically)
The on page error is in this text document.
[VueTorrent_404.txt](https://github.com/user-attachments/files/17090309/VueTorrent_404.txt)

Another issue is: I still cannot find the VueTorrent default username password. I tried admin & admin; admin & adminadmin, but nothing works. I even followed [this](https://github.com/qbittorrent/qBittorrent/wiki/I-forgot-my-UI-lock-password), but of no use.

### Expectations

Login should happen, or in the least should provide the path/place/page details. The image is a confusing thing for me. I cannot make head or tail of it, as to which page is missing, and what is the password for me to login.

Is there a config file where I can change the password manually for VueTorrent setup?

FYI: Did not try nightly, and do not wish to try that. Stable only.

### Relevant debug informations

This is what I am getting. Hard to type, so giving the image instead.
![image](https://github.com/user-attachments/assets/5f2077b4-6dcf-4cd6-b848-8abce75c7cbf)

### Steps to reproduce

1. Install manually via zip file (follow the wiki steps) Also followed the .htaccess steps [here](https://github.com/VueTorrent/VueTorrent/wiki/Alternative-Installation-Methods) for my apache2
2. go the page/url where the files are kept
3. use the login details

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type: (Desktop)
OS: (Windows - server is debian 12)
Browser: Librewolf (latest), Ungoogled Chromium, Waterfox (all latest ones)

PWA: Yes / No - No afaik?
Running inside a container: No, but on a VPS
```

### qBittorrent version

4.5.2 (qbt-nox)

### VueTorrent version

2.13.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by Larsluph** [comment]
The 404 you're getting is because you're using NGINX and probably misconfigured it. I don't think you should have the /public prefix in the URL, this may be what causes the 404s.

The WebUI tries to send a request to /api but is actually using /public/api to do so.

With all the information I can't help further. Just know that it's not related to VueTorrent.

**Comment by vdbhb59** [comment]
Thanks for the quick response.
The login URLs I gave are coming by default when I type my domain. I do not have NGINX, only Apache2. So not sure why I keep seeing 404, 405 errors (saw that in Dev mode on Librewolf).
Moreover, I am very much confused on the login username and password, which I cannot understand. What is the PWD mate? Or where can I reset it directly?

**Comment by Larsluph** [comment]
Yeah Apache sorry, whatever the problem is the same.

Password should be the one mentioned in the logs. But if you have a 404, that means the login request never reaches qbittorrent. Try accessing it directly without Apache to make sure everything works.

Can I ask why you are using Apache?

**Comment by vdbhb59** [comment]
Okay. Got your point mate. Apache is the default on my HestiaCP setup. For the password, I will look it up.
BTW, I think the issue seems to be with what you have mentioned for the targeted folder. I think I am unable to set them properly. Any command to get those fixed?
[Installation](https://github.com/VueTorrent/VueTorrent/wiki/Installation)
`$ ls -lh
total 8.0K
drwxrwsr-x+ 3 larsluph users 4.0K Jan 20 16:00 public
-rw-rw-r--  1 larsluph users    5 Jan  9 13:45 version.txt`

**Comment by Larsluph** [comment]
Permissions shouldn't matter much as long as you have read access with your apache worker user.

Try setting up the Apache server without the `/public` prefix. Unfortunately, I don't have much experience with Apache so I'm not able to assist you on that.
