### ISSUE TITLE
[DEBT]: Use custom logic for backend settings sync

### ISSUE THREAD

**Issue by Larsluph** [VueTorrent/VueTorrent#1919]
From #1918

Backend handshake is done at app init, before logging in. Thus, all settings sync are rejected when not using bypass or when using external auth service.

~As sync is done by pinia plugin, see if we can instruct storage hydration manually.~

~Delay async call until logged in?~

Improvements to be done after changes:
- Sync settings only when needed
- Prevent warning logs when using bare qBittorrent

**Comment by WDaan** [comment]
Or at least retry after login?

**Comment by Larsluph** [comment]
After research, we have no way to interact with the plugin. However, pinia API is public so anything a plugin can do, we can implement it in the app.

We might drop the plugin usage for the backend and add manual watchers instead. This will allow for better customization of behavior.
