### ISSUE TITLE
[Bug]: Can't pause anymore

### ISSUE THREAD

**Issue by QuarkZ26** [VueTorrent/VueTorrent#1938]
### Bug description

When hitting the pause button, nothing happens, whether I right-click or use the top bar button. Some other settings do not save at all.
I use the docker version and see:

QMetaObject::invokeMethod: No such method TorrentsController::pauseAction()
Bad Http request method, closing socket. IP: ::ffff:10.1.1.2. Method: "PUT"

### Expectations

it should work :P

### Relevant debug informations

I disabled the UI and it works with the default one. I think it started with 5.0 as I never had that issue before.

### Steps to reproduce

Try to pause a newly added torrent

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Qbittorrent docker
```

### qBittorrent version

5.0

### VueTorrent version

2.13.3

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by Larsluph** [comment]
see #1928
