### ISSUE TITLE
[Bug]: Unable to pause torrents with 5.0.0 on Truenas Scale 24

### ISSUE THREAD

**Issue by davidereitano** [VueTorrent/VueTorrent#1941]
### Bug description

Hi. Since the last update on Truenas i am no longer able to pause torrents, both right-clicking on single torrent and clicking the upper pause button for pause all

### Expectations

Clicking on pause will pause the torrent

### Relevant debug informations

Hi. Since the last update on Truenas i am no longer able to pause torrents, both right-clicking on single torrent and clicking the upper pause button for pause all

### Steps to reproduce

1. having an active torrent (downloading or stalled)
2. pause it

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
qBittorrent: 5.0.0
Operating system: Truenas Scale 24.04 / Kubernetes / Docker
Browser (name and version): Safari / Chrome

PWA: Yes
Running inside a container: Yes
```

### qBittorrent version

5.0.0

### VueTorrent version

2.13.3

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by terrytw** [comment]
See https://github.com/VueTorrent/VueTorrent/issues/1930 and https://github.com/VueTorrent/VueTorrent/pull/1928

**Comment by davidereitano** [comment]
sorry, i didn't checked. My fault. Closing and following 1930 and 1928
