### ISSUE TITLE
[Bug]: Torrent state is not taken into account when sorting with queue position

### ISSUE THREAD

**Issue by keroivanov1945** [VueTorrent/VueTorrent#1945]
### Bug description

Torrents with completed states (e.g.: seeding, uploading, done) precedes downloading torrents when sorting torrents by "Queue Position".

Sorting in ascending order:
![image](https://github.com/user-attachments/assets/7232eb21-d0f8-4e7a-bda3-628d3ebc93e6)

Sorting in descending order:
![image](https://github.com/user-attachments/assets/86ac0804-3ceb-4e1c-b3b9-ed68d1379796)

Depending on the number of torrents and page size, this can cause downloading torrents to pushed to the second page (in ascending order) or to have the torrent with the least priority on top (in descending order).

Possible workaround is to filter torrents by state and uncheck Done, Seeding, Uploading, Uploading [F] values, but it's cumbersome and also raises other issues (not seeing all torrents).

### Expectations

Downloading torrents should come before completed ones.

### Relevant debug informations

This is a regression of #1740 where the special handling of the queue position has been removed:
https://github.com/VueTorrent/VueTorrent/pull/1740/files#diff-cc9a919585e33e3844ef287f38df541d6c79687e3298f77d6f3e58ffab746d79L62-L67

---

In qBittorrent the downloading torrent's priority displayed with numbers and other torrents have an asterisk. A similar approach would fix the bug!

### Steps to reproduce

1. Seed a couple of torrents and have some in the queue too
2. Use table listing and sort by queue position

### How did you install VueTorrent?

Using a third-party docker image (hotio or others)

### Environment description

```plain text
Device type: all
OS: not applicable
Browser (name and version): Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

PWA: not applicable
Running inside a container: yes as Docker mod for qBittorrent container
```

### qBittorrent version

4.6.7

### VueTorrent version

2.13.3

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by keroivanov1945** [comment]
> Possible workaround is to filter torrents by state and uncheck Done, Seeding, Uploading, Uploading [F] values, but it's cumbersome and also raises other issues (not seeing all torrents).

In addition, it'd be great to have special filters:
- "Completed" (group for done, seeding, uploading)
- "In Progress" (group for everything else)

This would help to mitigate the issue if it's not easy fix!

**Comment by Larsluph** [comment]
This will be quick to adjust, thanks for pin-pointing the missing rule!

**Comment by Larsluph** [comment]
Hey, sorry for the delay.

Here's the updated build. LMK if this works out better.

[vuetorrent.zip](https://github.com/user-attachments/files/17285546/vuetorrent.zip)
