### ISSUE TITLE
[Bug]: Search Engine Download broken

### ISSUE THREAD

**Issue by PiperMp3** [VueTorrent/VueTorrent#1952]
### Bug description

Open Search Engine
Put search query (Anything)
Use Prowlarr as plugin or leave as "all" or "enabled" (doesnt matter)
Receive results
Click Download button
DevTools reporting 200 on DownloadTorrent post endpoint
No prompt at bottom of screen to add torrent

### Expectations

On VueTorrent 2.13 with qBit lower than 5.0 prompt would come at bottom of screen allowing torrent to be added.

### Relevant debug informations

No errors, positive http 200 response from /api/v2/search/downloadTorrent endpoint
Forgot to mention - there is no trace in the qbit system logs that anything actually happened, nothing about anything being added or failed to add or anything at all.

### Steps to reproduce

Open Search Engine
Put search query (Anything)
Use Prowlarr as plugin or leave as "all" or "enabled" (doesnt matter)
Receive results
Click Download button
DevTools reporting 200 on DownloadTorrent post endpoint
No prompt at bottom of screen to add torrent

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type: (Desktop / Laptop / Phone)
OS: (Windows 10 / Android 14 )
Browser (Windows - OperaGX V114.0.5282.21 / Microsoft Edge 129.0.2792.79 (Official build) (64-bit)
Phone - Chrome 129.0.6668.81 ): 

PWA: NA
Running inside a container: Yes
```

### qBittorrent version

5.0.0

### VueTorrent version

2.14.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by Larsluph** [comment]
The lack of feedback is expected behaviour, I felt like adding a toast each time you download something from a plugin might be too much.

It is a new feature from qBit 5, allowing to download torrents from plugins themselves, for handling authentication and other stuff.

Anyway you should find the torrent in the list after clicking on that download button.

**Comment by PiperMp3** [comment]
Thank you for responding.
I loved the toast line on the bottom, was amazing.

There may be something up with some settings, as regardless of how many times I click the download button inside the search engine, no torrent is added anywhere. 
Could you elaborate on 

> It is a new feature from qBit 5, allowing to download torrents from plugins themselves, for handling authentication and other stuff.

Ive had Qbit plugged in with Prowlarr via the UI for years, works just fine in standard UI.
Would you consider bringing back the bottom toast line as an option?

Right now I either need to use standard UI, or jump over to Prowlarr and add things from there. Vue just doesnt let me do any of that now.

**Comment by PiperMp3** [comment]
Scratch that, some setting got enabled somewhere.
So ok the items are now directly added as advised, that is correct.

Would love the bottom toast back though :D

**Comment by Larsluph** [comment]
> Would love the bottom toast back though :D

I just thought about something neat to do about that, I'll take a look right away 👀
