### ISSUE TITLE
[Bug]: Capacity calculation error

### ISSUE THREAD

**Issue by iwowcn** [VueTorrent/VueTorrent#1966]
### Bug description

- qBittorrent VueTorrent calculates 1.27 TB (incorrect)
- qBittorrent calculates 1.155 TB (correct)
- Transmission calculates 1.16 TB (correct)
- Synology DSM calculates 1.16 TB (correct)
![PixPin_2024-10-12_13-24-02](https://github.com/user-attachments/assets/ff4d8491-8c4b-4291-8c28-cefc9e187fd8)
![PixPin_2024-10-12_13-23-19](https://github.com/user-attachments/assets/17fd62ea-0434-44d1-be19-2e626b87d4b1)
![PixPin_2024-10-12_13-22-39](https://github.com/user-attachments/assets/f41ccef9-2a87-4fad-8fce-f528e2e8cd49)
![PixPin_2024-10-12_13-26-22](https://github.com/user-attachments/assets/e6c8a4c8-7a30-4734-b2a5-452aae486611)

### Expectations

Can correctly calculate and display storage capacity

### Relevant debug informations

none

### Steps to reproduce

1. Change to the qBittorrent UI, calculation is correct.
2. Change to the VueTorrent UI, calculation is incorrect.
...

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type: Synology DSM
OS: Windows / Synology DSM Docker
Browser (name and version): Google Chrome 129.0.6668.100

PWA: No
Running inside a container: Yes
```

### qBittorrent version

5.0.0

### VueTorrent version

2.14.1

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by Larsluph** [comment]
This is not a bug, it's a unit problem.

1.27 **TB** = 1,270,000,000,000 B = 1.155 **TiB**

VueTorrent uses the correct unit and you can toggle it in the settings if you wanna switch between TB and TiB.
