### ISSUE TITLE
[Bug]: Deleting a torrent along with deleting files will not delete files from the disk

### ISSUE THREAD

**Issue by agevlakh** [VueTorrent/VueTorrent#1979]
### Bug description

When I want to delete a torrent, I choose the option to delete it along with all the files. The torrent is deleted, but the files remain on the disk

### Expectations

I expect the files to be deleted along with the torrent itself if I choose that option

### Relevant debug informations

it turns out that the checkbox when deleting a torrent does not work

### Steps to reproduce

1 select torrent from list
2 delete it
3 select delete along with files
4 files are not deleted

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type: (Desktop)
OS: (Windows 10)
Browser (Edge latest): 

PWA: Yes / No
Running inside a container: No
```

### qBittorrent version

5.0.0

### VueTorrent version

2.14.1

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by Larsluph** [comment]
Without any proof that VueTorrent is at fault (request not sending the right parameters), I'm afraid it's a qBittorrent bug.

Try looking at the qBittorrent logs to see what it says, the message body changes whether the file box is checked or not.

I just tested it and it does send the expected value in all my tests.

**Comment by agevlakh** [comment]
> Without any proof that VueTorrent is at fault (request not sending the right parameters), I'm afraid it's a qBittorrent bug.


Hello. You were right. When disabling the third-party web interface vuetorrent, the behavior repeated. I will make a bug report in qBitTorrent

**Comment by agevlakh** [comment]
It is delete mode in advanced settings. Added trash option, if possible
https://github.com/qbittorrent/qBittorrent/issues/21245
