### ISSUE TITLE
[Bug]: Filtering out a torrent while in select mode should also deselect it

### ISSUE THREAD

**Issue by Nocifer** [VueTorrent/VueTorrent#1997]
### Bug description

Yeah, yeah, I know this is the umpteenth feature/bug report I'm filing in the space of a couple of days, but it's all for the greater good, I promise.

Now, the actual issue: selecting a torrent and then toggling some filter on/off which filters that torrent out doesn't also deselect it, which means that any further changes (adding/removing tags & categories, force rechecking, moving, pausing, even DELETING!!!1 - ask me how I know :P) will be applied to that torrent as well even though it isn't currently visible.

This is especially dangerous when multiple torrents are selected and then a new filter only filters a subset of them out, leaving the rest of them still visible and shown as selected, which doesn't at all imply that the other, now hidden, torrents are also still selected and any action performed on the visibly selected torrents will apply to the hidden selected torrents as well.

### Expectations

In select mode, torrents should be immediately deselected when they become non-visible (i.e. filtered out).

### Relevant debug informations

N/A

### Steps to reproduce

1. Select 2 or more torrents from at least 2 different categories.
2. Enable a filter for one of these categories: the torrent(s) that belong to this category will stay visible and selected, while the torrents that belong to the other categories will be hidden.
3. Right-click one of the visible selected torrents and add a new tag.
4. Disable the filter enabled in (2): you will see that the tag was applied to ALL torrents previously selected in (1), both those that stayed visible after (2) and those that were hidden.
5. Ponder the thought of what would have happened if instead of applying a tag, you had instead opted to delete the torrents along with their files.

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type: Desktop
OS: Arch Linux
Browser (name and version): Firefox 132

PWA: No
Running inside a container: No
```

### qBittorrent version

4.6.7

### VueTorrent version

2.15.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by Larsluph** [comment]
Please note that this isn't a bug but rather intended behavior, to prevent interfering with the selection on behalf of the user.

Because you didn't told the app to deselect torrents, the app doesn't deselect them for you.
