### ISSUE TITLE
[Feature Request]: read/unread rss elements more distinguishable in dark mode

### ISSUE THREAD

**Issue by bloodysneaker** [VueTorrent/VueTorrent#2029]
### Description

The title is self-explanatory.  The white and gray difference are pretty subtle in dark mode.

### Describe the solution you'd like

A colored "new" tag before the element title would be awesome. Something in the style of the state tags of the downloading torrents

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
Something like this?

![image](https://github.com/user-attachments/assets/48326f20-f912-42b6-88ff-66c2575e70d1)

**Comment by bloodysneaker** [comment]
Yeah I had something like that in mind
