### ISSUE TITLE
[Bug]: A couple of issues related to the "untracked" filter

### ISSUE THREAD

**Issue by terrytw** [VueTorrent/VueTorrent#2034]
### Bug description

With the newly implemented https://github.com/VueTorrent/VueTorrent/pull/2032, I have discovered a couple of problems:

0. First of all, it does work. I created a test torrent with `not working` tracker status, and it does show up when using "`Untracked` filter:
![1](https://github.com/user-attachments/assets/eae3a5e7-78ff-4a7f-bef3-774c135ee474)
![2](https://github.com/user-attachments/assets/7c75e374-743a-487c-8446-ee19b21d22de)

1. All torrents that is `done`(meaning they are finished and stopped, not seeding) also show up when using said filter. 
2. The number after `Untracked` is always `0` even when there are a lot of torrents showing up using said filter.
3. I personally strongly suggest we keep it consistent with the official implementation of the GUI, i.e., create a `torrent state filter` called `Tracker Error` for torrents with tracker but the tracker is not working. Leave `Untracked` for those torrents without tracker at all. 

### Expectations

All information included in Bug description section. 

### Relevant debug informations

All information included in Bug description section. 

### Steps to reproduce

All information included in Bug description section. 

### How did you install VueTorrent?

Using an official docker image (vuetorrent-lsio-mod, vuetorrent-backend)

### Environment description

```plain text
Device type: (Desktop)
OS: (Windows)
Browser (name and version): Chrome 118

PWA: No
Running inside a container: Yes
```

### qBittorrent version

5.0.1

### VueTorrent version

2.17.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by Larsluph** [comment]
> 1. All torrents that is done(meaning they are finished and stopped, not seeding) also show up when using said filter.

Probably because as the torrent isn't announced, qBittorrent considers the tracker as "failed", we must have a list of status to make exceptions on them.

> The number after Untracked is always 0 even when there are a lot of torrents showing up using said filter.

Right, I forgot to change that in the process.

> I personally strongly suggest we keep it consistent with the official implementation of the GUI, i.e., create a torrent state filter called Tracker Error for torrents with tracker but the tracker is not working. Leave Untracked for those torrents without tracker at all.

Now that I have everything, we are able to differentiate those, between the trackers list returning all torrents with trackers (untracked filter) and the `torrent.tracker` value indicating if a torrent has a working tracker (not_working filter).
