### ISSUE TITLE
[Bug]: Torrent number is wrong

### ISSUE THREAD

**Issue by terrytw** [VueTorrent/VueTorrent#2049]
### Bug description

1. It seems that in `tracker filter` the number in brackets are all wrong:
![1](https://github.com/user-attachments/assets/78d6ea21-0f2c-4e90-b8e6-5210e53058c7)
I would like to say the number is the seeding number, but apparently not because for one tracker it is like this:
![2](https://github.com/user-attachments/assets/96d853a0-214c-49ee-8bf9-9d353867638f)
I have pinpointed out the torrent which causes the discrepancy, it's the third one. (Tell me if you need information on that torrent) The same torrent is also weirdly `Done` but not in `Not working` (Related https://github.com/VueTorrent/VueTorrent/issues/2048)

### Expectations

Torrent number is correct

### Relevant debug informations

N/A

### Steps to reproduce

N/A

### How did you install VueTorrent?

Using an official docker image (vuetorrent-lsio-mod, vuetorrent-backend)

### Environment description

```plain text
Device type: (Desktop)
OS: (Windows)
Browser (name and version): chrome 118

PWA: No
Running inside a container: Yes
```

### qBittorrent version

5.0.1

### VueTorrent version

2.18.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by Larsluph** [comment]
This is linked to #2048.
Because offline torrents (including done) aren't announced, filters are not consistent.

The second case is still weird...

**Comment by Larsluph** [comment]
Please check with the nightly release after merge to confirm both are of the same root cause.

**Comment by terrytw** [comment]
Can you please tell me how to do it? I am using docker backend.

**Comment by Larsluph** [comment]
If you're using the LSIO mod, you can simply use the tag "nightly" instead of "latest".

For the backend you can switch branches using an environment variable, value will be "dev".

**Comment by terrytw** [comment]
I tried it using `RELEASE_TYPE=dev`, and it appears to be fixed. All of the problems reported here and in the other issue. 

Thanks!
