### ISSUE TITLE
[Bug]: Unacceptable file type, only regular file is allowed.

### ISSUE THREAD

**Issue by byjove01** [VueTorrent/VueTorrent#2058]
### Bug description

I want to access my qBittorrent service from my NAS, on my computer. But installing VueTorrent on it prevents me to access the UI as I get this error "Unacceptable file type, only regular file is allowed."

### Expectations

I expect the VueTorrent UI to show.

### Relevant debug informations

I'm using Docker.

### Steps to reproduce

1. Install VueTorrent
2. Run qBittorrent-nox
3. Go to the URL

### How did you install VueTorrent?

Downloaded from GitHub releases

### Environment description

```plain text
Device type: Desktop
OS: Arch Linux x86-646.11.8-arch1-2
Browser (name and version): LibreWolf 132.0.2-1
PWA: If that's the question, yes I'm using the Web UI
Running inside a container: Yes, Docker
```

### qBittorrent version

latest

### VueTorrent version

v2.18.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by Larsluph** [comment]
This error is thrown by qBittorrent when you didn't configure the WebUI folder properly.

Given that you use docker, make sure the VueTorrent folder you downloaded is mounted somewhere in your container.

Also you must set the unzipped `vuetorrent` folder in qBittorrent, containing both the `public` folder and the `version.txt` file.

**Comment by byjove01** [comment]
Mounted, it is.
```
    volumes:
      - /services/torrent/config:/config
      - /services/torrent/downloads:/downloads
      - /services/torrent/customui:/customui
```
It's the `customui` repository and it contains the `public` folder and `version.txt` file.

**Comment by Larsluph** [comment]
So if the `/customui` folder contains the `public` folder and is configured in the qBittorrent WebUI preferences, maybe there's permission issues?

```sh
# Open interactive shell in container
docker exec -it {container_name} sh

# Get ownership of webui folder content
ls -la /customui/public
```

**Comment by byjove01** [comment]
```
/ # ls -la /customui/public
total 60
drwxr-sr-x    4 root     root          4096 Nov 17 17:21 .
drwxrws---    3 root     989           4096 Nov 21 17:46 ..
-rw-r--r--    1 root     root          1001 Nov 17 17:21 apple-touch-icon.png
drwxr-sr-x    2 root     root          4096 Nov 17 17:21 assets
-rw-r--r--    1 root     root          5430 Nov 17 17:21 favicon.ico
-rw-r--r--    1 root     root          1062 Nov 17 17:21 icon-192.png
-rw-r--r--    1 root     root          1787 Nov 17 17:21 icon-512.png
-rw-r--r--    1 root     root           316 Nov 17 17:21 icon.svg
-rw-r--r--    1 root     root          1542 Nov 17 17:21 index.html
-rw-r--r--    1 root     root          2525 Nov 17 17:21 manifest.webmanifest
-rw-r--r--    1 root     root           122 Nov 17 17:21 registerSW.js
-rw-r--r--    1 root     root            26 Nov 17 17:21 robots.txt
drwxr-sr-x    2 root     root          4096 Nov 17 17:21 screenshots
-rw-r--r--    1 root     root            81 Nov 17 17:21 sw.js
```

```
/ # ls -la /customui/
total 16
drwxrws---    3 root     989           4096 Nov 21 17:46 .
drwxr-xr-x    1 root     root          4096 Nov 21 17:34 ..
drwxr-sr-x    4 root     root          4096 Nov 17 17:21 public
-rw-r--r--    1 root     root             6 Nov 17 17:21 version.txt

```

**Comment by Larsluph** [comment]
Nothing looks weird, you should have read access on all files.

Verify in qBittorrent logs that the served folder is the correct one.

**Comment by byjove01** [comment]
> Nothing looks weird, you should have read access on all files.
> 
> Verify in qBittorrent logs that the served folder is the correct one.

```
https://0x0.st/XRq3.txt
```
Sorry for the delay. Seems there's no noticeable problems.

**Comment by Larsluph** [comment]
The WebUI does look like it is configured properly, I have no idea what's the issue here.

Have you considered using other methods like the docker mod?

**Comment by byjove01** [comment]
Where can I find it? I didn't saw it on the main page - I didn't even know there was a docker mod for this.

**Comment by Larsluph** [comment]
You can find everything [in the wiki](https://github.com/VueTorrent/VueTorrent/wiki/Installation#using-lsio-docker-mod)

**Comment by Larsluph** [comment]
You can find everything [in the wiki](https://github.com/VueTorrent/VueTorrent/wiki/Installation#using-lsio-docker-mod)

**Comment by byjove01** [comment]
I am using qBittorrent-nox on a server without graphical server. Is that mod compatible with the qBittorrent-nox docker?

**Comment by Larsluph** [comment]
Only if you're using the image from linuxserver

**Comment by byjove01** [comment]
There isn't qBittorrent-nox docker image from linux server so I'll take that as a no.. Thanks anyways.

**Comment by Larsluph** [comment]
Well it does exist, you can look at the provided docker compose.

https://hub.docker.com/r/linuxserver/qbittorrent

**Comment by Larsluph** [comment]
> I still don't see anything related to qB -nox .

Well qBittorrent-nox is just the same app without the Qt layer for the GUI, which is what this image does under the hood.

> But it doesn't matter anymore, I did what you said and it barely seems it works but I can't access the Web GUI from my browser anymore.

I see in your logs that the app is served on a non-default port 8001. Make sure this port is mapped properly in your docker configuration.

You should see the native WebUI on the first container launch as the docker mod only loads vuetorrent inside a folder (`/vuetorrent`). You'll have to set the WebUI folder manually the first time.

> Connection is apparently refused according to Electron.

What do you mean by Electron? The WebUI has not been made to be used with Electron.

**Comment by byjove01** [comment]
> > I still don't see anything related to qB -nox .
> 
> Well qBittorrent-nox is just the same app without the Qt layer for the GUI, which is what this image does under the hood.

Ok then.

> > But it doesn't matter anymore, I did what you said and it barely seems it works but I can't access the Web GUI from my browser anymore.
> 
> I see in your logs that the app is served on a non-default port 8001. Make sure this port is mapped properly in your docker configuration.

Do you mean Docker actually gives itself the right to block specific ports? Unless you're talking about the docker compose file?

> You should see the native WebUI on the first container launch as the docker mod only loads vuetorrent inside a folder (`/vuetorrent`). You'll have to set the WebUI folder manually the first time.

Ok.

> > Connection is apparently refused according to Electron.
> 
> What do you mean by Electron? The WebUI has not been made to be used with Electron.

The same happens with LibreWolf (based on Firefox). I just used Electron to potentially get an hint about what's happening.

**Comment by Larsluph** [comment]
> Do you mean Docker actually gives itself the right to block specific ports? Unless you're talking about the docker compose file?

Every docker containers are isolated from your system by design. To access specific ports from your container to the outside world (either your computer or any local computer), you have to expose that port in your container configuration.

Given that your container is exposing the qBittorrent WebUI on URL `http://localhost:8001`, you'll have to expose the port 8001.

```yml
services:
  qbit:
    image: linuxserver/qbittorrent:latest
    ...
    ports:
      - "8001:8001"
```

**Comment by byjove01** [comment]
Then yes, the port is mapped to 8001. For a weird reason, I just can't access the WebUI.

**Comment by byjove01** [comment]
Ok, nevermind, it did work. You can close this as completed.
