### ISSUE TITLE
[Bug]: "Not working" filter is not updated

### ISSUE THREAD

**Issue by terrytw** [VueTorrent/VueTorrent#2061]
### Bug description

I have a couple of torrents that I have been seeding for a couple of weeks. They were working, but several days back the tracker had a technical issue and since then these torrents are not working.

But when using "Not working" filter, they don't show up. After restarting qbittorrent and vuetorrent, they show up.

I am guessing that the filter is not periodically updated?

### Expectations

When a torrent's tracker becomes not working, it should show up in "Not working" filter. 

### Relevant debug informations

N/A

### Steps to reproduce

1. Seed a torrent
2. Make the tracker not working

### How did you install VueTorrent?

Using an official docker image (vuetorrent-lsio-mod, vuetorrent-backend)

### Environment description

```plain text
Device type: (Desktop)
OS: (Windows)
Browser (name and version): chrome 118

PWA: No
Running inside a container: Yes
```

### qBittorrent version

5.0.1

### VueTorrent version

2.18.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by Larsluph** [comment]
If qBittorrent haven't been restarted then that may be why, as the way we "guess" that data is relying on whether torrent has already received data in the past.

**Comment by terrytw** [comment]
OK makes sense. So once the torrent is not working, qbit has to be restarted before vuetorrent cant correctly display "Not working".

It seems that best way forward is to have an official WebAPI for this. I have already put up an issue, but no one seems to be interested. https://github.com/qbittorrent/qBittorrent/issues/21796

**Comment by thesyntaxslinger** [comment]
Quite the opposite.
All trackers are shown as working, after a restart of qBittorrent, there is exactly 0 trackers that are "Not working" which isn't true.
It used to be they would all start as "Not working" and then gradually connect to the trackers.

**Comment by thesyntaxslinger** [comment]
Yeah sure. I can send you over anything you need.
I'm not 100% sure what you mean though, as none of them display as not working no matter what.
