### ISSUE TITLE
[Feature Request]: The size does not match the actual size

### ISSUE THREAD

**Issue by RexCcwll** [VueTorrent/VueTorrent#2062]
### Description

The size does not match the actual size. In the original qbittorrent, the size was 125.29GB, but in VueTrend it became 134GB

### Describe the solution you'd like

Is it possible to fix this to display the same size? Is there a difference between base 1000 and 1024?

### Complementary informations

- [X] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
Duplicate of #1966

**Comment by Larsluph** [comment]
qBittorrent does display GiB as GB, it's a common error
