### ISSUE TITLE
[Feature Request]: in torrent creator add the source section

### ISSUE THREAD

**Issue by pruebadelvue** [VueTorrent/VueTorrent#2068]
### Description

in qbitorrent 5.01 the source section appears but in vuetorrent it does not.

### Describe the solution you'd like

add it to vuetorrent for easy use.

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
Can you be more precise on the field you see missing?

The source field should be the first one in the create dialog.

**Comment by pruebadelvue** [comment]
Sorry for being imprecise, I'll show you a picture that looks better, it is the source section below tha says Source. Thanks for reply!
![How-to-create-a-private-torrent-using-qBittorrent](https://github.com/user-attachments/assets/a8699cbc-dcaa-4e59-93a4-af09cc4d44f0)

**Comment by Larsluph** [comment]
That's what I had in mind, this fields was incorrectly mapped and thus not read by the API, see qbittorrent/qBittorrent#21879

It will be released and used in qbit v5.0.3
