### ISSUE TITLE
[Bug]: Inconsistent torrent number

### ISSUE THREAD

**Issue by terrytw** [VueTorrent/VueTorrent#2072]
### Bug description

It's related to the "Not working" filter.
![1](https://github.com/user-attachments/assets/5a4eb0ae-0ef1-4186-9943-447aed4ac21e)

As shown in the screenshot, there are 2 torrents for this tracker that is "Not working", 198 is paused. But when filtering using this tracker, I got all 200 torrents, and the counter at bottom is 200, when in the bracket, it shows "198".

I think we should either make both of them 198, or 200. And if we make it 198, we should only filter the torrents that are not "Not working."

### Expectations

Consistent number shown and filtered. 

### Relevant debug informations

N/A

### Steps to reproduce

Have some torrents that are not working, and filter them. 

### How did you install VueTorrent?

Using an official docker image (vuetorrent-lsio-mod, vuetorrent-backend)

### Environment description

```plain text
Device type: (Desktop)
OS: (Windows)
Browser (name and version): chrome 118

PWA: No
Running inside a container: Yes
```

### qBittorrent version

5.0.1

### VueTorrent version

2.18.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by Larsluph** [comment]
This is fixed by the latest commit #2071

I was previously stopping counting trackers if detected as not working, I removed that part to continue counting.
