### ISSUE TITLE
[Feature Request]: Make horizontal scroll bar always visible

### ISSUE THREAD

**Issue by terrytw** [VueTorrent/VueTorrent#2079]
### Description

Right now the horizontal scroll  bar is only at bottom.

If we can get an option like the pagination to put additional scroll bar at top it would be great. 

### Complementary informations

- [ ] Is this feature already implemented in the default WebUI?

**Comment by Larsluph** [comment]
All scroll bars are currently handled by your browser, I'm not sure if it's worth the effort to replicate that behavior in the app...

**Comment by terrytw** [comment]
One alternative (now I think about it, this maybe better) is to put vertical scroll bar in the "torrent window" instead of the entire right panel. See this:
![1](https://github.com/user-attachments/assets/4f739d74-9424-49ad-9654-b334bf7e65d9)
The red rectangle is the "torrent window" I am talking about. If you put a scroll bar there instead of the current position, the horizontal scroll bar and the pagination should always be visible, thus solving the problem.

**Comment by Larsluph** [comment]
Then that's great!

I was just planning about doing something like that next after noticing that the infinite scroll wasn't handling large torrents as it should.

Setting the view's height to a fixed value should make everything stick to their position as expected.
