### ISSUE TITLE
[Feature Request]: Add Super Seeding toggle to contect menu

### ISSUE THREAD

**Issue by ToasterUwU** [VueTorrent/VueTorrent#2083]
### Description

In the default WebUI there is a button to turn on super seed mode. 
This makes it so that qbittorrent only uploads each block once, to make sure all the pieces get into the wild as soon as possible.

Its a niche thing, but for those few times where you are the only seeder out there, this can speed up transfer significantly.

Example: 1 Seeder normal mode with 10 Leeches would mean that some blocks get uploaded multiple times to different people, "wasting" the upload bandwith for something that the 10 Leeches could already share with each other.
With one "super" seeder, all the limited bandwith of the only seeder will be used to send missing pieces out, and then all the leeches share that piece with each other, maximizing the speed of getting a second seeder.

### Describe the solution you'd like

In the right click context menu, i would like to have a toggle. Next to the "Sequential Download" stuff should be fine.

### Complementary informations

- [X] Is this feature already implemented in the default WebUI?

**Comment by ToasterUwU** [comment]
I just realized that as a workaround, there is a toggle for this in the "Boolean Values" section of the Info tab of the torrent itself.

Very hidden, but at least its there. Still would prefer a button for it that is next to the other things people use. 
Idk  how this works in QBT itself and if the UI could even do it, but i would actually love it if it goes from super seeding to normal seeding automatically when it uploaded each block once.

**Comment by Larsluph** [comment]
> This makes it so that qbittorrent only uploads each block once, to make sure all the pieces get into the wild as soon as possible.

Thanks for the explanation! I already tried searching for what that super seeding mode does without success.

> Idk how this works in QBT itself and if the UI could even do it, but i would actually love it if it goes from super seeding to normal seeding automatically when it uploaded each block once.

WebUI is only an interface that fetches information from your qBittorrent instance and formats them to be "human-readable".

This kind of events are processed internally by qBittorrent for real-time efficiency, I know an option to enable super-seeding after some time but not the other way around.
