### ISSUE TITLE
[Bug]: backend/ping shows error 500

### ISSUE THREAD

**Issue by m33ts4k0z** [VueTorrent/VueTorrent#2105]
### Bug description

Opening the main qbittorrent WebUI using vuetorrent v 2.19.0 and qbittorrent 5.0.3, show this error on console. No other apparent issues exist and the application seems to function normally but I thought I drop it here.  

This error doesn't show if I disable vuetorrent.

### Expectations

I don't know what I would expect from that endpoint but at least, it wouldn't show an error.

### Relevant debug informations

```
index-BhWmfNB5.js:28 
        
        
GET http://10.0.0.36:8082/backend/ping 500 (Internal Server Error)
(anonymous) @ index-BhWmfNB5.js:28
xhr @ index-BhWmfNB5.js:28
fm @ index-BhWmfNB5.js:30
_request @ index-BhWmfNB5.js:31
request @ index-BhWmfNB5.js:30
Yi.<computed> @ index-BhWmfNB5.js:31
(anonymous) @ index-BhWmfNB5.js:26
ping @ index-BhWmfNB5.js:36
Re.immediate @ index-BhWmfNB5.js:845
await in Re.immediate
ri @ vue-DFryKk-1.js:14
bn @ vue-DFryKk-1.js:14
l.call @ vue-DFryKk-1.js:15
E @ vue-DFryKk-1.js:10
ri @ vue-DFryKk-1.js:14
jp @ vue-DFryKk-1.js:14
Promise.then
Vp @ vue-DFryKk-1.js:14
_u @ vue-DFryKk-1.js:14
l.scheduler @ vue-DFryKk-1.js:15
Py.f.scheduler @ vue-DFryKk-1.js:10
trigger @ vue-DFryKk-1.js:10
Ou @ vue-DFryKk-1.js:10
notify @ vue-DFryKk-1.js:10
trigger @ vue-DFryKk-1.js:10
set value @ vue-DFryKk-1.js:10
v @ index-BhWmfNB5.js:36
g @ index-BhWmfNB5.js:36
await in g
P @ vue-DFryKk-1.js:23
B @ index-BhWmfNB5.js:845
(anonymous) @ index-BhWmfNB5.js:845
(anonymous) @ vue-DFryKk-1.js:15
ri @ vue-DFryKk-1.js:14
bn @ vue-DFryKk-1.js:14
t.__weh.t.__weh @ vue-DFryKk-1.js:15
ss @ vue-DFryKk-1.js:5
D @ vue-DFryKk-1.js:15
run @ vue-DFryKk-1.js:10
$ @ vue-DFryKk-1.js:15
G @ vue-DFryKk-1.js:15
w @ vue-DFryKk-1.js:15
m @ vue-DFryKk-1.js:15
q @ vue-DFryKk-1.js:15
mount @ vue-DFryKk-1.js:15
Na.t.mount @ vue-DFryKk-1.js:19
(anonymous) @ index-BhWmfNB5.js:862
(anonymous) @ index-BhWmfNB5.js:862
```

The response also shows:

`Unacceptable file type, only regular file is allowed.`

### Steps to reproduce

Just open the main WebUI page of qbittorrent

### How did you install VueTorrent?

Fetched from latest-release branch as well as compiled latest nightly from source.

### Environment description

```plain text
Windows 11
Chrome Version 131.0.6778.205 (Official Build) (64-bit)
Firefox 133.0.3 (64-bit)
```

### qBittorrent version

5.0.3

### VueTorrent version

2.19.0

### Agreements

- [X] The bug still occurs on the nightly build
- [X] The bug still occurs on the latest version of qBittorrent
- [X] A similar issue doesn't already exist
- [X] I checked the DevTools and included any errors that may show up

**Comment by Larsluph** [comment]
This is required to detect if the backend is installed. If you don't have it installed that's expected!

**Comment by m33ts4k0z** [comment]
Hello.

Indeed I had no idea about the separate backend. I will spin up a docker container with it now on Unraid. Thanks a lot for your fast answer 😊
