### ISSUE TITLE
Use search bar instead of search icon

### ISSUE THREAD

**Issue by ticklemyIP** [VueTorrent/VueTorrent#891]
The current search bar is hidden behind an icon which is really unintuitive in my opinion it would be much better for the UI, and also one less button to click on, if it was an instant search bar. It could also be a bigger size than the current. The space is also there on moblie and desktop view.

![image126](https://github.com/WDaan/VueTorrent/assets/126688461/cafbba88-3cba-4835-a548-7f4797981b3a)

**Comment by oyrei** [comment]
This seems like a good suggestion.

**Comment by Larsluph** [comment]
I agree that there's a lot of space available on desktop but mobile is kind of limited, especially with the chip to see enabled filters 🤔

**Comment by ticklemyIP** [comment]
![Screenshot_20230708_220202_Brave](https://github.com/WDaan/VueTorrent/assets/126688461/ff43e56a-be7d-4615-b15b-fdd7396f3c41)
![Screenshot_20230708_220224_Brave](https://github.com/WDaan/VueTorrent/assets/126688461/6608a43b-d83f-49a0-8c3d-8e9138537c51)

Imo. there are plenty of space, if the + and dropdown menu icons at the top right temporarily disappears when searching there are even more.

**Comment by WDaan** [comment]
Mobile could be like Spotify playlist, show search on scroll up?

**Comment by ticklemyIP** [comment]
@WDaan Thank you for all the work!

**Comment by MyWebmasterD** [comment]
Hello,
also for me it's really counterintuitive to have the torrent search hidden behind an icon...how about a setting to show the search bar in the homepage?

**Comment by Larsluph** [comment]
@MyWebmasterD Fix is already implemented. Please update the app or open a new issue.

**Comment by MyWebmasterD** [comment]
oh sorry I am in the latest version but I can't find the setting, can you please help?

**Comment by Larsluph** [comment]
It is directly available in the latest version, there's no settings for it. You can check the [demo link](https://vuetorrent.github.io/demo/#/), it is always there, both on mobile and desktop.

**Comment by MyWebmasterD** [comment]
Also in the link you set me the top bar is to filter active torrents, not to search for new torrents

**Comment by Larsluph** [comment]
In that case you were probably confused with the search engine (the magnifying glass at the top right). You are talking about something different than the current issue.

**Comment by MyWebmasterD** [comment]
Yes I got it, I'm sorry
