### ISSUE TITLE
Add bulk selection to the Content list

### ISSUE THREAD

**Issue by ticklemyIP** [VueTorrent/VueTorrent#894]
We cant bulk select in the content view currently. This is annoying when trying to bulk select torrents not to download. This could also be a base for a bulk-rename feature.

**Comment by Misfi** [comment]
Upvoting this - this would be a huge QoL improvement. I often find myself switching to OG web UI to perform bulk operations on content.

**Comment by PitbullRaven** [comment]
I'll add my hat into the ring. Just found this Godsend of a UI today and it is great on mobile, though I can't select individual files or folders to stop. As soon as I deselect the entire thing, it always activate the last file or folder in the contents list. If I try and select something in the middle of the list, it selects the entire list again.
