### ISSUE TITLE
[Feature Request] Version Check

### ISSUE THREAD

**Issue by cybersholt** [VueTorrent/VueTorrent#941]
It would be great if on the setting page, it would check for a new version. And possibly add a setting to automatically check for updates and if there is one display a toast message. 

For now I have a little shell script that does this but it would be nice to see built in.

**Comment by WDaan** [comment]
Check for a new version is something we could do.

The updating itself however, not sure how we could accomplish that... the UI has no server access, it cannot change your local filesystem.
I don't think that's even possible without a custom BitTorrent server.

**Comment by cybersholt** [comment]
@WDaan cool, I know you can't self update from the UI but figured a notification would be helpful to the user and what I meant by automatically check for updates is that if the user selected that option and a new version came out a toast would be displayed, otherwise if the user is in the settings page display some text next to the current version saying theres an update or something like that. 

For those interested in a self update, here's what I've cobbled together: https://gist.github.com/cybersholt/2358fc69104433fbab54e273a9fda5fd

I'll probably change this script a little to run via cron and just auto update.

**Comment by cybersholt** [comment]
Something else that would be helpful from a self update prospective as well would be some way to determine the current version, right now I just set it manually but if there was a file or API method

**Comment by Larsluph** [comment]
> some way to determine the current version

No idea how we can access it externally but the info is available somewhere as we're able to fetch it from the app (actually you can see it if you go into the settings, under "Current version" inside the first settings page)

**Comment by Larsluph** [comment]
I tested on a local build and I found it lost in the middle of some obfuscated js code inside the 
`index-8ced1280.js` (name is not pre-defined so it will change at each build):
`function dj(){return"1.6.0"}`

You can search for this to extract the obfuscated function name: this.$store.commit("SET_APP_VERSION",dj())

**Comment by cybersholt** [comment]
Thanks @Larsluph, I was just about to start digging around in the source 😁
