### ISSUE TITLE
[Feature Request] Add *.torrent file association for PWA

### ISSUE THREAD

**Issue by srtaswer** [VueTorrent/VueTorrent#989]
By adding this feature, This PWA will be a great remote-thin-client replacement. 
I'm guessing there might be similarities with the magnet link handler (#111 #784) in the approach of achieving this.

https://learn.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/how-to/handle-files

**Comment by Larsluph** [comment]
Thanks for the request, this could be a great improvement to the PWA. The only thing that ticks is that it is an experimental feature, and it is not currently supported on many devices (especially mobile devices)
https://developer.mozilla.org/en-US/docs/Web/Manifest/file_handlers#browser_compatibility

**Comment by WDaan** [comment]
Is this the same as #673?

**Comment by Larsluph** [comment]
> Is this the same as #631?

This issue is for handling torrent files, whereas the mentioned issue is for handling magnet links when shared from another app
